"use client";

import { useEffect, useRef } from "react";
import { compileMessageTemplates, ENGLISH_UI_OVERRIDES } from "./english-ui-text";
import type { UiLanguage } from "./ui-language-preference";
import enPlatform from "./en-platform.json";
import enOrders from "./en-orders.json";
import enSettings from "./en-settings.json";

/**
 * Display-only compatibility layer for existing UI copy. Business evidence,
 * editable values and machine protocols are preserved, never rewritten in storage.
 */
export const READYWORK_ZH_CN_TEXT: Readonly<Record<string, string>> = Object.freeze({
  "Overview": "总览",
  "Notifications": "通知",
  "Drafted Emails": "邮件草稿",
  "Local": "本地采购",
  "Import": "进口采购",
  "Procurement Routes": "采购路径",
  "Reports": "报表",
  "Risk Dashboard": "风险看板",
  "Settings": "设置",
  "Suppliers": "供应商",
  "SLA": "服务等级",
  "Advanced SLA": "高级服务等级",
  "Configuration": "自动跟单",
  "PROCUREMENT ROUTES": "采购路径",
  "REPORTS": "报表",
  "SETTINGS": "设置",

  "Track and manage your purchase orders across all procurement routes.": "跟踪并管理所有采购路径中的采购订单。",
  "Calculating the persisted purchase order portfolio…": "正在计算已持久化的采购订单组合…",
  "High Risk": "高风险",
  "Medium Risk": "中风险",
  "Low Risk": "低风险",
  "Immediate action": "立即处理",
  "Overdue POs": "逾期采购订单",
  "Past required date": "已超过要求日期",
  "Require Attention": "需要关注",
  "Action needed": "需要处理",
  "Active Purchase Orders": "进行中的采购订单",
  "Across all routes": "覆盖所有路径",
  "Local Procurement": "本地采购",
  "Import Procurement": "进口采购",
  "Active POs": "进行中的采购订单",
  "Purchase Orders": "采购订单",
  "PO NUMBER": "采购订单号",
  "PO Number": "采购订单号",
  "SUPPLIER": "供应商",
  "ROUTE": "路径",
  "MATERIAL TYPE": "物料类型",
  "CURRENT STAGE": "当前阶段",
  "Current Stage": "当前阶段",
  "REQUIRED IN-HOUSE DATE (RIHD)": "要求到厂日期（RIHD）",
  "Required In-House Date (RIHD)": "要求到厂日期（RIHD）",
  "RISK": "风险",
  "NEXT ACTION": "下一步操作",
  "Next Action": "下一步操作",
  "ACTIONS": "操作",
  "Actions": "操作",
  "Route": "路径",
  "Material Type": "物料类型",
  "Stage": "阶段",
  "Risk": "风险",
  "Supplier": "供应商",
  "All": "全部",
  "Unclassified": "未分类",
  "unclassified": "未分类",
  "Supplier Commitment": "供应商承诺",
  "Fulfilment / Production": "履约／生产",
  "Dispatch": "发运",
  "Delivery Completed & GRN": "交付完成并收货",
  "PO Sent": "采购订单已发送",
  "High": "高",
  "Medium": "中",
  "Low": "低",
  "Obtain supplier confirmation": "获取供应商确认",
  "Confirm production status": "确认生产状态",
  "Track dispatch": "跟踪发运",
  "Verify receipt and ERP GRN": "核验收货与 ERP 收货单",
  "Review current execution status": "检查当前执行状态",
  "View details": "查看详情",
  "Send follow-up": "发送催办",
  "Edit RIHD": "编辑要求到厂日期",
  "Mark at risk": "标记为风险",
  "Previous page": "上一页",
  "Next page": "下一页",
  "AI Procurement Summary": "AI 采购摘要",
  "TODAY'S HIGHLIGHTS": "今日重点",
  "Review High-Risk POs": "查看高风险采购订单",
  "Review Unclassified POs": "查看未分类采购订单",
  "Awaiting Supplier": "等待供应商",
  "Delivery Risk": "交付风险",
  "On Track": "按计划推进",
  "Stay ahead. Take action.": "提前掌握，及时行动。",
  "No change": "无变化",
  "Insufficient data": "数据不足",
  "New": "新增",
  "Trend available after 2 saved snapshots": "保存至少 2 个快照后可查看趋势",
  "Persisted portfolio snapshot trend": "已持久化的采购组合快照趋势",
  "Quick ranges": "快捷范围",
  "Today": "今天",
  "Last 7 days": "最近 7 天",
  "Last 30 days": "最近 30 天",
  "This quarter": "本季度",
  "Year to date": "今年至今",
  "Previous month": "上个月",
  "Next month": "下个月",
  "Apply": "应用",
  "Cancel": "取消",
  "Clear filters": "清除筛选",
  "Select overview trend date range": "选择总览趋势日期范围",
  "Overview trend date range": "总览趋势日期范围",
  "Month calendar": "月历",
  "Purchase order filter results": "采购订单筛选结果",
  "Search PO number, supplier…": "搜索采购订单号或供应商…",
  "Showing": "显示第",
  "of": "项，共",
  "entries": "项",
  "Overdue": "逾期",
  "d": "天",
  "— Risk Overview": "— 风险概览",

  "Inbox": "收件箱",
  "Notification Center": "通知中心",
  "Notification center": "通知中心",
  "Mark all as read": "全部标为已读",
  "All notifications": "全部通知",
  "Unread": "未读",
  "Read": "已读",
  "No notifications": "暂无通知",
  "No unread notifications": "没有未读通知",
  "Loading notifications…": "正在加载通知…",
  "Refresh": "刷新",

  "Agent-drafted follow-ups & escalations — review, edit, and approve.": "AI 员工起草的催办与升级邮件——请审核、编辑并批准。",
  "Edit draft": "编辑草稿",
  "To": "收件人",
  "Subject": "主题",
  "Body": "正文",
  "Edit reason": "编辑原因",
  "Explain why the recipient or content changed for the audit trail": "说明修改收件人或内容的原因，以便审计留痕",
  "Saving…": "正在保存…",
  "Save changes": "保存更改",
  "Approve & Send": "批准并发送",
  "Edit": "编辑",
  "Discard": "丢弃",
  "Select a drafted email to review it.": "请选择一封邮件草稿进行审核。",
  "No published SLA policy is available.": "尚无已发布的服务等级策略。",
  "No professional sender identity is configured.": "尚未配置专业发件人身份。",
  "No drafted emails are available.": "暂无邮件草稿。",
  "Configure SLA": "配置服务等级",
  "Open Configuration": "打开配置",
  "Configure a supplier-visible sender identity first": "请先配置供应商可见的发件人身份",
  "Approve and enter the real delivery queue": "批准并进入真实发送队列",

  "Monitor procurement risks and their potential impact": "监控采购风险及其潜在影响",
  "Risk Overview": "风险概览",
  "Risk Distribution": "风险分布",
  "Risk Trends": "风险趋势",
  "Top Risk Factors": "主要风险因素",
  "At-Risk Purchase Orders": "有风险的采购订单",
  "Search purchase orders…": "搜索采购订单…",
  "Export": "导出",
  "Loading risk dashboard…": "正在加载风险看板…",
  "No risk data is available.": "暂无风险数据。",

  "Supplier Directory": "供应商目录",
  "Supplier Performance": "供应商绩效",
  "Search suppliers…": "搜索供应商…",
  "Add Supplier": "添加供应商",
  "Total Suppliers": "供应商总数",
  "Active Suppliers": "活跃供应商",
  "On-Time Delivery": "准时交付",
  "Average Lead Time": "平均交付周期",
  "Contact": "联系人",
  "Location": "所在地",
  "Performance": "绩效",
  "Status": "状态",
  "Active": "启用",
  "Inactive": "停用",
  "Search by supplier name, email, country, or supplier ID": "按供应商名称、邮箱、国家或供应商编号搜索",

  "SLA Settings": "服务等级设置",
  "Advanced SLA Settings": "高级服务等级设置",
  "Service Level Agreements": "服务等级协议",
  "Escalation Rules": "升级规则",
  "Follow-up Rules": "催办规则",
  "Save": "保存",
  "Publish": "发布",
  "Published": "已发布",
  "Draft": "草稿",
  "Create Rule": "创建规则",
  "Add Rule": "添加规则",
  "Rule name": "规则名称",
  "Policy intent / scope": "策略意图／范围",
  "Enable automatic send": "启用自动发送",
  "Stages allowlist": "阶段允许列表",
  "Channels allowlist": "渠道允许列表",
  "Risks allowlist": "风险允许列表",
  "Draft publication": "草稿发布状态",
  "Current runtime": "当前运行状态",
  "Delete": "删除",
  "Deactivate": "停用",
  "Details": "详情",
  "Common": "通用信息",
  "Rule ID": "规则编号",
  "Company Code": "公司代码",
  "Business Unit": "业务单元",
  "Effective From": "生效日期",
  "Effective To": "失效日期",
  "Priority": "优先级",
  "Created By": "创建人",
  "Approved By": "批准人",
  "Last Updated": "最后更新",
  "Notes": "备注",
  "Delete rule?": "删除规则？",
  "This removes the rule from the current draft. Save the draft to persist the deletion.": "这会从当前草稿中移除规则；保存草稿后删除才会持久化。",

  "General Settings": "常规设置",
  "Agent Setup": "智能体设置",
  "Business Systems": "业务系统",
  "Auto-send": "自动发送",
  "Advanced Governance": "高级治理",
  "Manage global settings for SLA, lead time calculations and notification agents.": "管理服务等级、交付周期计算和通知智能体的全局设置。",
  "Save Changes": "保存更改",
  "Configuration sections": "配置分区",
  "1. General Settings": "1. 常规设置",
  "Configure global preferences for SLA and lead time calculations.": "配置服务等级与交付周期计算的全局偏好。",
  "2. Agent Setup": "2. 智能体设置",
  "Configure communication channels for notifications and escalations.": "配置通知和升级所用的通信渠道。",
  "Auto-send follow-ups": "自动发送催办",
  "All gates ready": "所有门禁均已就绪",
  "Server policy": "服务端策略",
  "Published profile": "已发布配置",
  "Stage allowlist": "阶段允许列表",
  "Channel allowlist": "渠道允许列表",
  "Risk allowlist": "风险允许列表",
  "Not published": "未发布",
  "None": "无",
  "Open server policy": "打开服务端策略",
  "Readiness gates": "就绪门禁",
  "Read-only from API": "来自 API 的只读数据",
  "Open server auto-send policy": "打开服务端自动发送策略",
  "Administrator governance boundary": "管理员治理边界",

  "Summary": "摘要",
  "Receipts": "收货",
  "Exceptions": "例外事项",
  "Timeline": "时间线",
  "Activity": "活动",
  "Files": "文件",
  "Send Email": "发送邮件",
  "Reassign": "重新指派",
  "Request Update": "请求更新",
  "Edit Purchase Order": "编辑采购订单",
  "Cancel Purchase Order": "取消采购订单",
  "Overview & Details": "概览与详情",
  "Order Lines": "订单明细",
  "Delivery": "交付",
  "Payment": "付款",
  "Owner": "负责人",
  "Created": "创建时间",
  "Updated": "更新时间",
  "Send email": "发送邮件",
  "Request update": "请求更新",
  "Edit purchase order": "编辑采购订单",
  "Cancel purchase order": "取消采购订单",

  "Readywork Assistant": "Readywork 助手",
  "Hello Admin! 👋": "管理员，您好！👋",
  "Attach file": "添加附件",
  "Send": "发送",
  "Readywork Assistant can make mistakes. Please verify important information.": "Readywork 助手可能会出错，请核实重要信息。",
  "Refresh history": "刷新历史记录",

  "Product": "产品",
  "How it works": "工作原理",
  "Risk visibility": "风险可视化",
  "FAQ": "常见问题",
  "Request a Demo": "申请演示",
  "Legal": "法律信息",
  "Effective": "生效日期",
  "Last updated": "最后更新",
  "On this page": "本页内容",
  "Pre-release disclosure.": "预发布声明。",
  "Privacy Policy": "隐私政策",
  "Terms of Use": "使用条款",
  "Readywork Procurement Execution · Pre-release": "Readywork 采购执行 · 预发布",

  "Readywork Procurement Execution": "Readywork 采购执行",
  "AI for procurement execution": "采购执行智能助手",
  "Keep every PO on track.": "让每一张采购订单都按计划推进。",
  "From": "从",
  "to": "到",
  "GRN.": "收货。",
  "We help procurement teams keep every PO on track with AI that follows up with suppliers, tracks deliveries and identifies risks early.": "Readywork 通过 AI 催办供应商、跟踪交付并及早识别风险，帮助采购团队让每张采购订单都按计划推进。",
  "View Product Overview": "查看产品概览",
  "Connects to the tools you already run": "连接您正在使用的工具",
  "The problem": "现状问题",
  "After a PO is sent, procurement teams chase suppliers across fragmented channels, tracking deliveries and risks in spreadsheets": "采购订单发出后，采购团队仍需在分散的渠道中催办供应商，并用电子表格跟踪交付和风险",
  ", a process that fails at scale.": "；随着规模扩大，这套方式很快失效。",
  "Your ERP": "您的 ERP",
  "Verified PO evidence": "已核验的采购订单证据",
  "Evidence required": "需要证据",
  "Execution leaves the system here.": "执行流程从这里离开业务系统。",
  "Email": "电子邮件",
  "Phone calls": "电话",
  "Spreadsheets": "电子表格",
  "awaiting source event": "等待来源事件",
  "connection required": "需要连接",
  "not configured": "未配置",
  "human evidence": "人工证据",
  "validation required": "需要核验",
  "Supplier follow-ups, delivery tracking and issue resolution, all manually coordinated across fragmented channels.": "供应商催办、交付跟踪和问题解决，全都要人工跨多个分散渠道协调。",
  "Trace": "追溯",
  "supplier coordination back to the purchase order and its evidence": "将供应商协作追溯到采购订单及其证据",
  "Detect": "识别",
  "missing confirmations and timing risks before a due date is missed": "在到期前识别确认缺失和时间风险",
  "Decide": "决策",
  "keep material discrepancies with the accountable procurement owner": "由负责的采购人员处理重大差异",
  "The gap": "关键缺口",
  "The risk is visible before the PO becomes late.": "采购订单逾期之前，风险就已经显现。",
  "Supplier commitment is still unverified.": "供应商承诺仍未核验。",
  "No response": "尚未回复",
  "The configured acknowledgement window elapsed.": "配置的确认时限已经过去。",
  "Quantity evidence conflicts with the purchase order.": "数量证据与采购订单不一致。",
  "An approval dependency is still pending.": "仍有前置审批待处理。",
  "By the time the due date is missed,": "等到错过到期日时，",
  "the signal was already there.": "风险信号其实早已出现。",
  "Execution summary": "执行摘要",
  "No persisted data. Evidence-backed conclusions appear after a verified source event.": "暂无持久化数据。核验来源事件后才会显示有证据支持的结论。",
  "The solution": "解决方案",
  "Know what needs attention before the PO becomes late.": "在采购订单逾期前，提前知道哪些事项需要关注。",
  "Readywork drafts the follow-up. Your team approves.": "Readywork 起草催办邮件，由您的团队批准。",
  "Not a system notification. A procurement professional your suppliers know.": "这不是系统通知，而是供应商熟悉的专业采购身份。",
  "Readywork communicates only through a verified named identity and approved channel. Every accepted message remains linked to its PO and connector receipt.": "Readywork 仅通过已核验的实名身份和获批渠道进行沟通。每条已接受的消息都会关联对应采购订单和连接器回执。",
  "Every PO is managed through five stages,": "每张采购订单都经过五个阶段管理，",
  "from PO Sent to GRN.": "从订单发出一直到收货。",
  "The purchase order is created and sent to the supplier.": "创建采购订单并发送给供应商。",
  "The supplier confirms the order and commits to the delivery.": "供应商确认订单并承诺交付。",
  "Production is underway; progress is tracked until goods are ready.": "生产开始后持续跟踪进度，直至货物备妥。",
  "Dispatch / Transit": "发运／在途",
  "Goods are dispatched and in transit to the destination.": "货物已发运，正在运往目的地。",
  "Delivery / GRN": "交付／收货",
  "Goods receipt, cross-checked against your ERP GRN.": "完成收货，并与 ERP 收货记录交叉核验。",
  "What this looks like on a real PO": "真实采购订单中的执行方式",
  "An SLA target and grace period for every stage. Escalations fire automatically when a supplier goes quiet.": "为每个阶段设置服务等级目标和宽限期；供应商久未回复时自动升级。",
  "Follow-ups by email and WhatsApp until the stage is confirmed, every message logged against the PO.": "通过邮件和 WhatsApp 持续催办直至阶段确认，每条消息都记录到采购订单。",
  "Import document verification before logistics handover; delivery cross-checked against your ERP GRN.": "物流交接前核验进口文件；交付结果与 ERP 收货记录交叉核对。",
  "A lifecycle view remains empty until verified stage evidence is persisted.": "只有持久化已核验的阶段证据后，生命周期视图才会显示内容。",
  "See where procurement execution is at risk": "查看采购执行中的风险位置",
  "before delivery is missed.": "在错过交付前采取行动。",
  "From chasing individual POs to managing execution risk across the portfolio.": "从逐张催办采购订单，升级为管理整个采购组合的执行风险。",
  "Customer value": "客户价值",
  "Grow procurement capacity": "提升采购产能",
  ", not coordination effort.": "，而不是增加协调负担。",
  "The same team can manage more POs with greater confidence.": "同一团队可以更从容地管理更多采购订单。",
  "Manual coordination": "人工协调",
  "follow-up": "催办",
  "call note": "通话记录",
  "tracker": "跟踪表",
  "message": "消息",
  "supplier reply": "供应商回复",
  "conversation": "会话",
  "Every PO chased by hand, across every channel.": "每张采购订单都要在各个渠道中人工催办。",
  "AI-supported execution": "AI 辅助执行",
  "Source evidence": "来源证据",
  "Commitment": "承诺",
  "Production evidence": "生产证据",
  "Fulfilment": "履约",
  "Connector receipt": "连接器回执",
  "Required": "必需",
  "Same Team, Greater Capacity.": "同一团队，更大产能。",
  "Verified source": "已核验来源",
  "Assigned route": "已分配路径",
  "Current receipt": "当前回执",
  "No persisted data": "暂无持久化数据",
  "Why Readywork": "为什么选择 Readywork",
  "Supervised procurement execution with tenant isolation, evidence gates, human approval and connector receipts built into every material action.": "以监督式方式执行采购，并将租户隔离、证据门禁、人工审批和连接器回执内置于每项重要操作。",
  "Frequently asked questions": "常见问题",
  "Does Readywork replace my procurement team?": "Readywork 会取代我的采购团队吗？",
  "No. Readywork handles supervised coordination work while your team retains material decisions, supplier relationships and approval authority.": "不会。Readywork 负责受监督的协调工作，重大决策、供应商关系和审批权仍由您的团队掌握。",
  "How does Readywork fit with an ERP?": "Readywork 如何与 ERP 协同？",
  "Readywork manages procurement execution after a PO is sent and complements the transaction system you already use.": "Readywork 管理采购订单发出后的执行工作，与您现有的交易系统形成互补。",
  "It follows up with suppliers, tracks verified progress and surfaces missing evidence without becoming a second ERP.": "它负责催办供应商、跟踪已核验进度并揭示证据缺口，而不会成为第二套 ERP。",
  "What identity do suppliers see?": "供应商会看到什么身份？",
  "Readywork communicates only through a named professional procurement identity configured for your organisation. If that identity is not configured and verified, external communication remains blocked.": "Readywork 只使用贵组织配置的实名专业采购身份沟通。该身份未配置并核验前，外部通信会保持阻止状态。",
  "Do I need to connect my ERP to get started?": "开始使用前必须连接 ERP 吗？",
  "No. Readywork can start from an approved email inbox and verified PO evidence. You can connect your ERP when ready; both modes keep the same audit trail.": "不必。Readywork 可以从获批邮箱和已核验的采购订单证据开始；准备好后再连接 ERP，两种模式都会保留相同的审计轨迹。",
  "How long does it take to go live?": "上线需要多长时间？",
  "Email-only setup can move quickly once identity, mailbox security and approval policy are verified. ERP integration depends on the systems and scope selected.": "身份、邮箱安全和审批策略核验后，纯邮件方案即可快速启用；ERP 集成周期取决于所选系统和范围。",
  "Is my data secure?": "我的数据安全吗？",
  "Credentials are encrypted, inbound documents pass explicit security gates and critical actions are audited. Deployment-specific security and residency controls are reviewed before production activation.": "凭据会加密，入站文档通过明确的安全门禁，关键操作均可审计；正式启用前还会审核部署专属的安全和数据驻留控制。",
  "What happens when Readywork detects a discrepancy?": "Readywork 检测到差异时会怎样？",
  "Readywork flags it to the relevant internal owner with the PO, supplier evidence, policy and executable options. The material decision stays with your team.": "Readywork 会把差异连同采购订单、供应商证据、策略和可执行选项提交给相关内部负责人，重大决策仍由您的团队作出。",
  "Request a demo": "申请演示",
  "Let's put Readywork on your POs.": "让 Readywork 开始管理您的采购订单。",
  "Start with a defined PO scope. We'll configure identity, mailbox security, approval policy and the execution route before any external action is enabled.": "先确定采购订单范围。在启用任何外部操作前，我们会配置身份、邮箱安全、审批策略和执行路径。",
  "The pilot remains supervised. Supplier communication and ERP writes stay blocked until the required identity, approval and connector checks are complete.": "试点全程受监督。完成所需身份、审批和连接器检查前，供应商通信和 ERP 写入均保持阻止状态。",
  "Pilot boundary": "试点边界",
  "A selected PO scope, supplier set and execution route.": "选定的采购订单范围、供应商集合和执行路径。",
  "External actions": "外部操作",
  "Enabled only after explicit production verification.": "只有通过明确的生产验证后才会启用。",
  "Every accepted request is persisted and auditable.": "每项已接受的请求都会持久化并可供审计。",
  "No supplier or ERP action runs from this form.": "此表单不会触发任何供应商或 ERP 操作。",
  "Start with a scoped pilot": "从限定范围的试点开始",
  "Tell us a little about your operation and we'll configure Readywork around your POs.": "请简要介绍您的业务，我们会围绕您的采购订单配置 Readywork。",
  "Employee Pack": "员工包",
  "Evidence-backed": "证据支持",
  "Product standard": "产品标准",
  "Readywork Procurement Execution · V1": "Readywork 采购执行 · V1",
  "Versioned workflows, governed actions, real connector requirements and tenant-isolated business data.": "版本化工作流、受治理操作、真实连接器要求与租户隔离的业务数据。",
  "Review the execution model →": "查看执行模型 →",
  "AI for procurement execution that follows up with suppliers, tracks deliveries and identifies risks early, from PO to GRN.": "面向采购执行的 AI：从采购订单到收货，催办供应商、跟踪交付并及早识别风险。",
  "Request a scoped pilot": "申请限定范围的试点",
  "View execution model": "查看执行模型",
  "Company": "公司",
  "Desktop Web · 1280×720 / 1440×900 / 1920×1080": "桌面网页 · 1280×720 / 1440×900 / 1920×1080",
  "Procurement Execution Employee Pack · Pre-release": "采购执行员工包 · 预发布",

  "The request could not be saved. Please try again.": "无法保存申请，请重试。",
  "Your request is saved.": "您的申请已保存。",
  "The request has been stored for human follow-up. No external email or CRM action was sent automatically.": "申请已保存，后续将由人工联系。系统没有自动发送外部邮件或执行 CRM 操作。",
  "Reference:": "申请编号：",
  "Submit another request": "再提交一份申请",
  "Full name *": "姓名 *",
  "Work email *": "工作邮箱 *",
  "Company *": "公司 *",
  "Role": "职位",
  "Country": "国家／地区",
  "ERP system": "ERP 系统",
  "Select...": "请选择…",
  "Other": "其他",
  "No ERP": "未使用 ERP",
  "Monthly PO volume": "每月采购订单量",
  "Under 100": "少于 100 张",
  "100 to 500": "100 至 500 张",
  "What should the pilot cover? (optional)": "希望试点覆盖哪些内容？（选填）",
  "A selected group of purchase orders, a supplier region, an import route...": "例如一组采购订单、某个供应商区域或一条进口路径…",
  "Saving request": "正在保存申请",
  "No commitment. Success appears only after storage; no supplier or ERP action runs from this form.": "无需承诺。只有成功保存后才会显示完成状态；此表单不会触发供应商或 ERP 操作。",

  "Privacy Policy | Readywork Procurement Execution": "隐私政策 | Readywork 采购执行",
  "Terms of Use | Readywork Procurement Execution": "使用条款 | Readywork 采购执行",
  "Pre-release": "预发布",
  "1 September 2026": "2026 年 9 月 1 日",
  "Scope and current status": "适用范围与当前状态",
  "This disclosure covers the public product website and demo request form, plus the authenticated procurement execution workspace operated by this deployment.": "本声明适用于公开产品网站和演示申请表，也适用于本部署所运行、需要身份验证的采购执行工作区。",
  "The product is still in supervised V1 validation. The final controller, processor, contracting entity and official privacy contact have not yet been approved for commercial publication.": "本产品仍处于受监督的 V1 验证阶段。最终的数据控制者、处理者、签约实体和官方隐私联系人尚未获准对外商业发布。",
  "Controller and processor roles": "控制者与处理者角色",
  "For a production customer, the customer organisation is expected to control its purchase orders, supplier contacts, correspondence and operational decisions. The deployment operator processes those records only for the configured procurement workflow and under the eventual customer agreement.": "对于生产环境客户，客户组织负责控制其采购订单、供应商联系人、往来通信和运营决策。部署运营方仅会依据已配置的采购工作流和最终客户协议处理这些记录。",
  "A supplier receiving a message should direct data requests to the buying organisation identified in that message. External messages remain blocked until a named professional procurement identity is configured and verified.": "收到消息的供应商应向消息中标明的采购组织提出数据请求。在实名专业采购身份配置并核验前，外部消息将保持阻止状态。",
  "Information collected on the public website": "公开网站收集的信息",
  "The demo form requires a full name, work email and company. Role, country, ERP, monthly PO volume and pilot notes are optional. A hidden anti-bot field is rejected by the server.": "演示申请表必填姓名、工作邮箱和公司；职位、国家／地区、ERP、每月采购订单量和试点说明为选填项。服务器会拒绝隐藏的反机器人字段。",
  "Accepted requests are validated, stored in SQLite with a stable request identifier and accompanied by an append-only submission event. Submission does not automatically send email, write a CRM or start a procurement workflow.": "获接受的申请会经过校验，以稳定申请编号存入 SQLite，并记录仅追加的提交事件。提交表单不会自动发送邮件、写入 CRM 或启动采购工作流。",
  "Information processed in the workspace": "工作区处理的信息",
  "The authenticated workspace may process purchase orders and lines, supplier master data and contacts, inbound and outbound email evidence, attachments, confirmations, approvals, production progress, shipment and receipt records, SLA evaluations, connector receipts, notifications and audit events.": "需要身份验证的工作区可能处理采购订单及明细、供应商主数据与联系人、收发邮件证据、附件、确认、审批、生产进度、发运和收货记录、服务等级评估、连接器回执、通知及审计事件。",
  "Records are tenant-scoped. The product does not intentionally expose one tenant's procurement records to another tenant, and unauthenticated business API requests are rejected.": "记录按租户隔离。本产品不会有意将一个租户的采购记录暴露给另一租户，未经身份验证的业务 API 请求会被拒绝。",
  "Cookies, logs and external assets": "Cookie、日志与外部资源",
  "The public pages do not require an application session. The authenticated workspace uses a strictly necessary HttpOnly, SameSite session cookie; the token is not stored in browser localStorage.": "公开页面无需应用会话。需要身份验证的工作区仅使用严格必要的 HttpOnly、SameSite 会话 Cookie；令牌不会存储在浏览器 localStorage 中。",
  "No analytics or advertising SDK is present in the current Console source. Public logos are served from Readywork-owned local paths or rendered as local React visuals; the product page does not request reference-product media. Routine server and connector logs may contain request time, status and technical diagnostics.": "当前控制台源码不含分析或广告 SDK。公开标识由 Readywork 自有本地路径提供或由本地 React 组件渲染；产品页不会请求参考产品媒体。常规服务器和连接器日志可能包含请求时间、状态及技术诊断信息。",
  "AI processing and human oversight": "AI 处理与人工监督",
  "AI and deterministic rules may extract supplier replies, identify missing facts, draft follow-ups and recommend actions. Material discrepancies, high-risk decisions and actions outside configured authority remain subject to human approval.": "AI 和确定性规则可提取供应商回复、识别缺失事实、起草催办信息并建议操作。重大差异、高风险决策和超出配置权限的操作仍须人工审批。",
  "Model providers, regions, data-use terms and retention must be frozen in the deployment and customer agreement before production. This pre-release page does not promise a provider or training policy that has not been configured and verified.": "正式生产前，模型提供方、区域、数据使用条款和保留规则必须在部署及客户协议中明确冻结。本预发布页面不会承诺尚未配置和核验的提供方或训练策略。",
  "Connectors and subprocessors": "连接器与分处理者",
  "Data may be exchanged only with connectors explicitly configured for the tenant, such as email, ERP/Odoo, workflow runtime, object storage, malware scanning or an approved model runtime. Connector success is recorded only after a real receipt is returned.": "数据只能与租户明确配置的连接器交换，例如电子邮件、ERP/Odoo、工作流运行时、对象存储、恶意软件扫描或获批的模型运行时。只有返回真实回执后，连接器操作才会记录为成功。",
  "The final subprocessor list, hosting location and cross-border transfer mechanism remain commercial-launch prerequisites and will be published after the deployment architecture and contracts are approved.": "最终分处理者清单、托管地点和跨境传输机制仍是商业上线的前置条件，将在部署架构和合同获批后公布。",
  "Security and audit": "安全与审计",
  "The implemented controls include authentication, role checks, tenant isolation, encrypted connector credentials, attachment type and malware gates, idempotency, optimistic versions, append-only events and auditable external-action receipts.": "已实现的控制包括身份验证、角色检查、租户隔离、连接器凭据加密、附件类型与恶意软件门禁、幂等性、乐观版本、仅追加事件以及可审计的外部操作回执。",
  "No system is risk-free. Production activation also requires healthy connectors, zero unresolved dead letters, reviewed security incidents and a verified recovery procedure.": "任何系统都并非零风险。正式启用还要求连接器健康、无未解决的死信、安全事件已复核，并具备经过验证的恢复流程。",
  "Retention, deletion and rights": "保留、删除与权利",
  "Procurement and audit records are currently preserved to support traceability and recovery. A binding retention schedule, deletion process, legal holds and data-subject response procedure have not yet been approved.": "当前会保留采购与审计记录，以支持追溯和恢复。具有约束力的保留期限、删除流程、诉讼保全和数据主体响应程序尚未获批。",
  "Before commercial launch, these periods and procedures must be documented by data category and reconciled with the customer's controller obligations, ERP records and signed agreement.": "商业上线前，必须按数据类别记录这些期限与程序，并与客户作为控制者的义务、ERP 记录和已签署协议保持一致。",
  "Contact and changes": "联系与变更",
  "During pre-release evaluation, privacy questions should be sent to the deployment owner who provided access. An official public privacy address will be added only after the operating entity confirms it.": "预发布评估期间，请将隐私问题发送给提供访问权限的部署负责人。只有运营实体确认后，才会添加官方公开隐私联系地址。",
  "Material changes to data collection, connectors, AI providers or retention should update this page and its effective date before the affected production capability is enabled.": "数据收集、连接器、AI 提供方或保留规则发生重大变化时，应在启用受影响的生产能力前更新本页面及其生效日期。",
  "How this pre-release procurement execution employee currently collects, uses and protects information on the public website and in the authenticated workspace.": "说明这款预发布采购执行员工目前如何在公开网站和需要身份验证的工作区中收集、使用与保护信息。",

  "About these terms": "关于本条款",
  "These pre-release terms describe use of the public product website and demo request form. They do not govern a pilot, trial or production deployment of the procurement workspace.": "本预发布条款说明公开产品网站和演示申请表的使用方式，不适用于采购工作区的试点、试用或生产部署。",
  "Commercial platform access must be governed by a separate signed agreement covering scope, fees, service levels, data protection, confidentiality, support, liability and termination.": "商业平台访问必须由另行签署的协议约束，涵盖范围、费用、服务等级、数据保护、保密、支持、责任和终止。",
  "Pre-release product status": "预发布产品状态",
  "The product is under active V1 validation and is not represented as generally available. Screenshots explain the intended interaction model; business records in the authenticated workspace come from the connected tenant systems and are not created from those screenshots.": "本产品正处于 V1 主动验证阶段，不代表已普遍可用。截图仅说明预期交互模式；需要身份验证的工作区中的业务记录来自已连接的租户系统，不会由截图生成。",
  "Named identity, published SLA policy, verified route evidence and a real PO-to-GRN closed loop remain production gates.": "实名身份、已发布的服务等级策略、已核验的路径证据以及真实的采购订单到收货闭环仍是生产门禁。",
  "Permitted use": "允许的使用方式",
  "You may use the public pages to evaluate the product, share them internally for that evaluation and submit a genuine demo request using information you are authorised to provide.": "您可以使用公开页面评估产品、在组织内部共享以供评估，并使用您有权提供的信息提交真实的演示申请。",
  "Access to the authenticated workspace is limited to accounts and tenant data authorised by the deployment owner.": "需要身份验证的工作区仅限部署负责人授权的账户和租户数据访问。",
  "Prohibited use": "禁止的使用方式",
  "You must not attempt unauthorised access, cross tenant boundaries, introduce malware, overload endpoints, bypass approval or connector gates, submit another person's details without authority, or misrepresent a generated recommendation as an approved business decision.": "您不得尝试未经授权的访问、跨越租户边界、引入恶意软件、使端点过载、绕过审批或连接器门禁、未经授权提交他人信息，或将生成的建议冒充为已获批准的业务决策。",
  "Supplier attachments and messages are untrusted inputs and must not be used to instruct the system outside the approved procurement workflow.": "供应商附件和消息均属于不可信输入，不得用于指示系统执行已批准采购工作流之外的操作。",
  "Demo requests": "演示申请",
  "A demo form submission is an enquiry only. Acceptance by the API means the validated request and audit event were persisted; it does not create a contract, guarantee a response time, start a pilot or authorise email, ERP or supplier actions.": "提交演示表单仅表示咨询。API 接受意味着已校验的申请和审计事件已持久化；这不会形成合同、保证响应时间、启动试点，也不会授权邮件、ERP 或供应商操作。",
  "Any scope, timing, price or production commitment requires a separate written agreement.": "任何范围、时间、价格或生产承诺均需另行签署书面协议。",
  "Platform agreement and customer authority": "平台协议与客户权限",
  "The customer organisation remains responsible for procurement authority, supplier relationships, lawful instructions, business rules, approved users and the accuracy of ERP and communication data supplied to the platform.": "客户组织仍负责采购权限、供应商关系、合法指令、业务规则、获批用户，以及提供给平台的 ERP 和通信数据的准确性。",
  "The signed platform agreement must prevail over this website for any pilot or production deployment.": "任何试点或生产部署均应以已签署的平台协议为准，而非本网站内容。",
  "AI output, supervision and external actions": "AI 输出、监督与外部操作",
  "AI summaries, extractions and recommendations may be incomplete or wrong and must be reviewed in context. Material discrepancies remain human decisions.": "AI 摘要、提取和建议可能不完整或有误，必须结合上下文审核；重大差异仍由人工决策。",
  "An interface label or draft is not proof that an email was sent, an ERP was updated or a stage completed. Those outcomes are recognised only after the configured connector returns a verifiable receipt and the audit chain records it.": "界面标签或草稿不能证明邮件已发送、ERP 已更新或阶段已完成。只有已配置连接器返回可验证回执且审计链完成记录后，才会确认这些结果。",
  "Intellectual property and third-party materials": "知识产权与第三方材料",
  "Third-party names, logos, libraries and services remain the property of their respective owners. References to SAP, QuickBooks, Gmail, Outlook, Office 365, WhatsApp, WeChat or Odoo do not imply affiliation or endorsement.": "第三方名称、标识、程序库和服务仍归各自所有者所有。提及 SAP、QuickBooks、Gmail、Outlook、Office 365、WhatsApp、WeChat 或 Odoo 并不表示存在关联或背书。",
  "Readywork public visuals are self-owned. Libraries and services are reviewed in the third-party component licence ledger, and any component without production entitlement remains unavailable for commercial release.": "Readywork 公开视觉素材为自有资产。程序库和服务会在第三方组件许可台账中审核，任何不具备生产使用权的组件均不得用于商业发布。",
  "Availability and warranties": "可用性与保证",
  "The public website and pre-release workspace may change, pause or contain defects. No production uptime, response-time, integration or outcome warranty is created by this page.": "公开网站和预发布工作区可能发生变化、暂停或存在缺陷。本页面不构成对生产可用时间、响应时间、集成或结果的任何保证。",
  "Production warranties and service levels must be stated in the signed customer agreement and supported by the deployed monitoring and recovery controls.": "生产保证和服务等级必须在已签署的客户协议中载明，并由已部署的监控与恢复控制提供支持。",
  "Liability, governing law and contact": "责任、适用法律与联系",
  "Liability limits, indemnities, governing law, jurisdiction, the operating legal entity and official notice addresses have not yet been approved. They must not be inferred from another company's public website or terms.": "责任限制、赔偿、适用法律、管辖地、运营法律实体和正式通知地址尚未获批，不得从其他公司的公开网站或条款中推断。",
  "During evaluation, questions should be sent to the deployment owner who provided access. These terms must receive legal review before any commercial launch.": "评估期间，请将问题发送给提供访问权限的部署负责人。任何商业上线前，本条款必须经过法律审核。",
  "The pre-release conditions for evaluating this public product website, and the boundary between a website enquiry and a separately contracted procurement deployment.": "说明评估本公开产品网站的预发布条件，以及网站咨询与另行签约的采购部署之间的边界。",
  "This page records the behavior currently implemented in this deployment. The operating legal entity, official contact, retention schedule, subprocessors, governing law and commercial contract terms must be approved before commercial launch. It is not legal advice or a substitute for a signed customer agreement.": "本页记录当前部署已实现的行为。运营法律实体、官方联系人、保留期限、分处理者、适用法律和商业合同条款均须在商业上线前获批。本页不构成法律建议，也不能替代已签署的客户协议。",

  "Breadcrumb": "面包屑导航",
  "Escalations, PO events, SLA alerts and system messages.": "集中查看升级事项、采购订单事件、服务等级告警和系统消息。",
  "Loading…": "正在加载…",
  "Pending": "待处理",
  "On schedule": "按计划推进",
  "Awaiting Confirmation": "等待确认",
  "Awaiting supplier confirmation": "等待供应商确认",
  "Human decision required": "需要人工决策",
  "Send purchase order": "发送采购订单",
  "Review complete audit trail": "查看完整审计记录",
  "This session does not have permission to read the purchase order portfolio.": "当前会话无权读取采购订单组合。",
  "The purchase order portfolio could not be loaded. Please try again.": "无法加载采购订单组合，请重试。",
  "Select a complete date range.": "请选择完整的日期范围。",
  "The start date cannot be later than the end date.": "开始日期不能晚于结束日期。",
  "Reads persisted snapshot trends only and never creates a new snapshot.": "仅读取已持久化的快照趋势，不会创建新快照。",
  "Clear": "清除",
  "Clear summary filter": "清除摘要筛选",
  "Not set": "未设置",
  "Unavailable": "不可用",
  "No persisted purchase orders match the current filters.": "没有符合当前筛选条件的已持久化采购订单。",
  "No persisted portfolio risks require a summary.": "当前没有需要摘要的已持久化采购组合风险。",
  "Readywork surfaces persisted risk evidence early so your team can keep every purchase order on track.": "Readywork 提前呈现已持久化的风险证据，帮助团队保持每张采购订单按计划推进。",
  "Just now": "刚刚",
  "You're all caught up": "全部已处理",
  "No procurement notifications yet": "暂无采购通知",
  "All procurement activity has been reviewed.": "所有采购活动均已查看。",
  "Changes to purchase orders, SLAs, connectors or receipts will appear here.": "采购订单、服务等级、连接器或回执的变更将显示在此。",
  "Acknowledgement follow-up": "确认催办",
  "Production progress follow-up": "生产进度催办",
  "Dispatch follow-up": "发运催办",
  "Delivery escalation": "交付升级",
  "Receipt follow-up": "收货催办",
  "Queued": "已排队",
  "Waiting for connector receipt": "等待连接器回执",
  "Sent": "已发送",
  "Failed": "失败",
  "Discarded": "已丢弃",
  "Changes saved and recorded in the audit trail": "更改已保存并记录到审计轨迹",
  "Needs attention — connector unavailable; delivery was safely blocked": "需要关注——连接器不可用，发送已安全阻止",
  "Queued — waiting for connector receipt": "已排队——等待连接器回执",
  "Discard this drafted email? This action will be recorded in the audit trail.": "丢弃这封邮件草稿？此操作将记录到审计轨迹。",
  "Draft discarded and recorded in the audit trail": "草稿已丢弃并记录到审计轨迹",
  "No drafted emails need review.": "暂无需审核的邮件草稿。",
  "Manage and track all local purchase orders": "管理并跟踪全部本地采购订单",
  "Manage and track all import purchase orders": "管理并跟踪全部进口采购订单",
  "Local Procurement route assistant": "本地采购路径助手",
  "Import Procurement route assistant": "进口采购路径助手",
  "Local POs Readywork Assistant": "本地采购订单 Readywork 助手",
  "Import POs Readywork Assistant": "进口采购订单 Readywork 助手",
  "Ask anything about your Local POs": "可询问与本地采购订单有关的任何问题",
  "Ask anything about your Import POs": "可询问与进口采购订单有关的任何问题",
  "Expand panel": "展开面板",
  "New chat": "新建会话",
  "Close assistant": "关闭助手",
  "I'm Readywork Assistant. Ask me anything about your local purchase orders. I can help you with:": "我是 Readywork 助手。您可以询问任何与本地采购订单有关的问题，我可以协助：",
  "I'm Readywork Assistant. Ask me anything about your import purchase orders. I can help you with:": "我是 Readywork 助手。您可以询问任何与进口采购订单有关的问题，我可以协助：",
  "PO status and details": "采购订单状态与详情",
  "Supplier information": "供应商信息",
  "Delivery timelines": "交付时间线",
  "Risks and issues": "风险与问题",
  "Spend analysis": "支出分析",
  "Show POs by supplier": "按供应商查看采购订单",
  "POs due this week": "本周到期的采购订单",
  "High risk POs": "高风险采购订单",
  "Choose File": "选择文件",
  "All POs": "全部采购订单",
  "Completed": "已完成",
  "Filters": "筛选",
  "Date Range": "日期范围",
  "Days to RIHD": "距要求到厂天数",
  "Total Value": "总金额",
  "Row Actions": "行操作",
  "Search by PO number, supplier…": "按采购订单号或供应商搜索…",
  "No confirmed Local Procurement POs yet": "暂无已确认的本地采购订单",
  "No confirmed Import Procurement POs yet": "暂无已确认的进口采购订单",
  "Transit Tracking": "在途跟踪",
  "No purchase orders match the current filters": "没有符合当前筛选条件的采购订单",
  "Adjust the stage, search, risk, supplier, or date filters.": "请调整阶段、搜索、风险、供应商或日期筛选条件。",
  "Loading persisted risk snapshots…": "正在加载已持久化的风险快照…",
  "Select risk snapshot date range": "选择风险快照日期范围",
  "The portfolio changed after this snapshot": "此快照之后采购组合已发生变化",
  "Update Risk Snapshot": "更新风险快照",
  "Update Snapshot": "更新快照",
  "HIGH RISK PO %": "高风险采购订单占比",
  "Share of active purchase orders with a published high-risk score.": "已发布高风险评分的进行中采购订单占比。",
  "HIGH RISK POS": "高风险采购订单",
  "Active purchase orders with a published risk score from 70 to 100.": "已发布风险评分为 70 至 100 的进行中采购订单。",
  "MEDIUM RISK POS": "中风险采购订单",
  "Active purchase orders with a published risk score from 40 to 69.": "已发布风险评分为 40 至 69 的进行中采购订单。",
  "LOW RISK POS": "低风险采购订单",
  "Active purchase orders with a published risk score from 0 to 39; an increase usually indicates lower portfolio risk.": "已发布风险评分为 0 至 39 的进行中采购订单；数量增加通常表示组合风险降低。",
  "AT RISK VALUE": "风险金额",
  "Value of at-risk POs; currencies remain separate when no exchange rate is configured.": "风险采购订单金额；未配置汇率时按币种分别显示。",
  "Currencies remain separate without configured FX rates": "未配置汇率时按币种分别显示",
  "vs previous snapshot": "与上次快照相比",
  "CNY no change": "人民币无变化",
  "Risk score publication status": "风险评分发布状态",
  "Legacy risk snapshot · read only": "旧版风险快照 · 只读",
  "Historical algorithm shown from its original snapshot; no V2 backfill.": "历史算法按原始快照展示，不进行 V2 回填。",
  "Risk Score Distribution": "风险评分分布",
  "Total POs": "采购订单总数",
  "High Risk (70-100)": "高风险（70–100）",
  "Medium Risk (40-69)": "中风险（40–69）",
  "Low Risk (0-39)": "低风险（0–39）",
  "Risk Breakdown": "风险构成",
  "Current Period": "本期",
  "Previous Period": "上期",
  "Delivery Delay": "交付延期",
  "Product Criticality": "产品关键程度",
  "Compliance & Approval": "合规与审批",
  "Risk by Supplier (Top 10)": "供应商风险（前 10 名）",
  "Risk Score (0-100)": "风险评分（0–100）",
  "At Risk Value": "风险金额",
  "Legacy score · evidence coverage unavailable": "旧版评分 · 无法获取证据覆盖率",
  "View all suppliers": "查看全部供应商",
  "Overdue Open POs by Aging Bucket": "逾期未结采购订单账龄分布",
  "No. of POs": "采购订单数量",
  "1 - 7 Days": "1–7 天",
  "8 - 14 Days": "8–14 天",
  "15 - 30 Days": "15–30 天",
  "31 - 60 Days": "31–60 天",
  "> 60 Days": "超过 60 天",
  "Products Affected by Delayed POs (Top 10)": "受延期采购订单影响的产品（前 10 名）",
  "Delayed POs": "延期采购订单",
  "Risk Trend (Based on Avg. Risk Score)": "风险趋势（基于平均风险评分）",
  "Risk Score (0-100) · persisted snapshots only": "风险评分（0–100）· 仅使用已持久化快照",
  "High Risk Purchase Orders": "高风险采购订单",
  "Risk Level": "风险等级",
  "Risk Score": "风险评分",
  "Risk Drivers": "风险驱动因素",
  "Required In-House Date": "要求到厂日期",
  "PO Value": "采购订单金额",
  "Legacy · High": "旧版 · 高",
  "No next action was recorded in this historical snapshot": "此历史快照未记录下一步操作",
  "View all high risk POs": "查看全部高风险采购订单",
  "Read persisted snapshots within the selected range.": "读取选定范围内的已持久化快照。",
  "Apply Dates": "应用日期",
  "Risk Snapshot Filters": "风险快照筛选",
  "Filters apply to KPIs, charts, trends and CSV exports.": "筛选条件会应用于 KPI、图表、趋势和 CSV 导出。",
  "All risk levels": "全部风险等级",
  "Procurement Route": "采购路径",
  "All routes": "全部路径",
  "All suppliers": "全部供应商",
  "All material types": "全部物料类型",
  "Clear Filters": "清除筛选",
  "Apply Filters": "应用筛选",
  "No risk snapshot in the selected date range": "选定日期范围内没有风险快照",
  "Creating a snapshot reads real POs, exceptions, supplier replies, connector results and required in-house dates. It does not modify purchase orders or trigger external actions.": "创建快照仅读取真实采购订单、例外、供应商回复、连接器结果和要求到厂日期；不会修改采购订单或触发外部操作。",
  "Create First Snapshot": "创建首个快照",
  "No previous snapshot": "无上一个快照",
  "No value change from the previous snapshot": "与上一个快照相比金额无变化",
  "Matches current portfolio": "与当前采购组合一致",
  "Provisional": "暂定",
  "Score not published": "评分未发布",

  "Manage and maintain all supplier master data used across procurement workflows.": "管理和维护采购工作流中使用的全部供应商主数据。",
  "Search by supplier name, code, country…": "按供应商名称、代码或国家／地区搜索…",
  "Supplier status": "供应商状态",
  "At Risk": "存在风险",
  "Supplier Code": "供应商代码",
  "Supplier Name": "供应商名称",
  "Type": "类型",
  "On Time Delivery %": "准时交付率",
  "Loading suppliers…": "正在加载供应商…",
  "Material Lead Times (SLA)": "物料交付周期（服务等级）",
  "Per supplier-material manufacturing lead times — the master the risk engine checks the moment a PO is raised. One supplier can carry a different cycle per material.": "按供应商和物料维护制造交付周期；采购订单创建时风险引擎会立即核对。同一供应商的不同物料可以设置不同周期。",
  "Add Lead Time": "添加交付周期",
  "Material": "物料",
  "Item Code": "物料代码",
  "Lead Time": "交付周期",
  "Criticality": "关键程度",
  "Remarks": "备注",
  "No lead-time rows yet.": "暂无交付周期记录。",
  "Add one per supplier + material so Readywork can assess required dates the moment a PO is sent.": "请按供应商与物料添加记录，以便 Readywork 在采购订单发出时立即评估要求日期。",
  "No suppliers match your search.": "没有符合搜索条件的供应商。",
  "Add New Supplier": "新增供应商",
  "Create a new supplier master record.": "创建新的供应商主数据记录。",
  "Save Supplier": "保存供应商",
  "Edit Supplier": "编辑供应商",
  "Update this supplier's master record.": "更新该供应商的主数据记录。",
  "Unnamed supplier": "未命名供应商",
  "Edit supplier": "编辑供应商",
  "Manage lead times": "管理交付周期",
  "View purchase orders": "查看采购订单",
  "Reactivate": "重新启用",
  "Supplier Information": "供应商信息",
  "Supplier Code *": "供应商代码 *",
  "Enter supplier code": "输入供应商代码",
  "Supplier Name *": "供应商名称 *",
  "Enter supplier name": "输入供应商名称",
  "Country *": "国家／地区 *",
  "Route *": "路径 *",
  "Select route": "选择路径",
  "Type *": "类型 *",
  "Select type": "选择类型",
  "Direct": "直接采购",
  "Indirect": "间接采购",
  "Contact Information": "联系信息",
  "Contact Person *": "联系人 *",
  "Enter contact person": "输入联系人",
  "Email *": "邮箱 *",
  "Enter email": "输入邮箱",
  "Phone *": "电话 *",
  "Enter phone number": "输入电话号码",
  "Use the WhatsApp number if that's how you reach this supplier.": "如果通过 WhatsApp 联系该供应商，请使用对应号码。",
  "Select country": "选择国家／地区",
  "Search countries…": "搜索国家／地区…",
  "Deactivate supplier": "停用供应商",
  "Reactivate supplier": "重新启用供应商",
  "Reason *": "原因 *",
  "Supplier status reason": "供应商状态变更原因",
  "Operating profile": "运营信息",
  "Profile version": "配置版本",
  "Not created": "未创建",
  "Master & contact": "主数据与联系人",
  "Source": "来源",
  "Score": "评分",
  "Evidence": "证据",
  "On-time": "准时率",
  "Open latest PO": "打开最新采购订单",
  "No purchase orders for this supplierId.": "该供应商暂无采购订单。",
  "Close": "关闭",

  "Configure service level agreements (SLA) for procurement processes.": "配置采购流程的服务等级协议。",
  "Add New Rule": "新增规则",
  "Search SLA rules": "搜索服务等级规则",
  "Search by process, description, supplier…": "按流程、描述或供应商搜索…",
  "Applies To": "适用对象",
  "All Suppliers": "全部供应商",
  "Local Suppliers": "本地供应商",
  "Import Suppliers": "进口供应商",
  "Process / Stage": "流程／阶段",
  "Description": "说明",
  "SLA Target": "服务等级目标",
  "Grace Period": "宽限期",
  "Escalation After": "升级时间",
  "Edit rule": "编辑规则",
  "More Actions": "更多操作",
  "Saved": "已保存",
  "Draft v2 · Saved": "草稿 v2 · 已保存",
  "SLA rule saved to the versioned draft.": "服务等级规则已保存到版本化草稿。",
  "SLA rule duplicated in the versioned draft.": "服务等级规则已在版本化草稿中复制。",
  "SLA rule deleted from the versioned draft.": "服务等级规则已从版本化草稿中删除。",
  "No SLA rules match your filters.": "没有符合当前筛选条件的服务等级规则。",
  "No SLA rules yet. Add a rule to create a versioned draft.": "暂无服务等级规则。添加规则以创建版本化草稿。",
  "No published policy": "暂无已发布策略",
  "Policy Governance & Runtime": "策略治理与运行状态",
  "Rule change confirmation": "规则变更确认",
  "Close rule removal": "关闭规则删除对话框",
  "Add New SLA Rule": "新增服务等级规则",
  "Edit SLA Rule": "编辑服务等级规则",
  "Define a service-level target for a procurement stage.": "为采购阶段定义服务等级目标。",
  "Update this service-level target.": "更新该服务等级目标。",
  "Process / Stage *": "流程／阶段 *",
  "Description *": "说明 *",
  "Escalation After must not be earlier than SLA Target plus Grace Period.": "升级时间不得早于服务等级目标加宽限期。",
  "Save Rule": "保存规则",

  "Configure the operational rules Readywork uses to monitor purchase orders — by section, manually or via CSV.": "按分区手动配置或通过 CSV 导入 Readywork 用于监控采购订单的运营规则。",
  "SLA sections": "服务等级分区",
  "Production & Service": "生产与服务",
  "Production / Service Milestones": "生产／服务里程碑",
  "Communication and Escalation Rules": "沟通与升级规则",
  "Commercial": "商务",
  "Payment Term Rules": "付款条款规则",
  "Logistics": "物流",
  "Logistics Planning Rules": "物流规划规则",
  "Logistics Handover Requirements": "物流交接要求",
  "Transit & Customs": "运输与海关",
  "Transit Monitoring Rules": "在途监控规则",
  "Regulatory and Import Approval Rules": "监管与进口审批规则",
  "Customs Clearance Rules": "清关规则",
  "Receipt & Closure": "收货与关闭",
  "Quality Inspection and GRN Rules": "质量检验与收货规则",
  "The standard fulfilment process per supplier-item / service — what should happen, how long it takes and when an update is due.": "按供应商物料／服务定义标准履约流程：应发生什么、需要多久以及何时应更新。",
  "Search rules…": "搜索规则…",
  "Template": "模板",
  "Upload CSV": "上传 CSV",
  "Advanced SLA data views": "高级服务等级数据视图",
  "Rules": "规则",
  "Validation Results": "校验结果",
  "Upload History": "上传历史",
  "Version History": "版本历史",
  "No rules in this section": "此分区暂无规则",
  "Rules are loaded only from the persisted Advanced SLA profile. No example records are generated for this empty state.": "规则仅从已持久化的高级服务等级配置加载；空状态不会生成示例记录。",
  "Configuration name": "配置名称",
  "Create v2 draft": "创建 v2 草稿",
  "Read-only access": "只读访问",
  "Policy settings": "策略设置",
  "Save draft": "保存草稿",
  "Schema v1 is read-only": "Schema v1 为只读",
  "Section enabled": "启用当前分区",
  "Resume": "恢复运行",
  "Pause": "暂停运行",
  "Retire": "退役",
  "Read only": "只读",
  "No rules match the current filters.": "没有符合当前筛选条件的规则。",
  "Add first rule": "添加首条规则",
  "No current draft validation issues": "当前草稿无校验问题",
  "No validation batch for this domain": "当前分区暂无校验批次",
  "No persisted upload history": "暂无已持久化的上传历史",
  "No persisted version events": "暂无已持久化的版本事件",
  "Unsaved local changes": "本地更改尚未保存",
  "Persisted state loaded": "已加载持久化状态",
  "Keep in draft": "保留在草稿中",

  "China": "中国",
  "Singapore": "新加坡",
  "Japan": "日本",
  "United Kingdom": "英国",
  "Germany": "德国",
  "United States": "美国",
  "Select the default country for calendar and holiday configuration.": "选择日历和节假日配置所使用的默认国家／地区。",
  "Working Days": "工作日",
  "Mon": "周一",
  "Tue": "周二",
  "Wed": "周三",
  "Thu": "周四",
  "Fri": "周五",
  "Sat": "周六",
  "Sun": "周日",
  "Select working days to be considered for SLA and lead time calculations.": "选择服务等级和交付周期计算采用的工作日。",
  "Enable SLA Escalations": "启用服务等级升级",
  "Enable escalation rules when SLA thresholds are breached.": "超过服务等级阈值时启用升级规则。",
  "Exclude Weekends": "排除周末",
  "Exclude weekends from SLA and lead time calculations.": "服务等级和交付周期计算不计周末。",
  "Exclude Public Holidays": "排除公共节假日",
  "Exclude country-specific public holidays from calculations.": "计算时排除特定国家／地区的公共节假日。",
  "Auto-calculate Lead Time": "自动计算交付周期",
  "Automatically calculate and update lead time based on active rules.": "根据生效规则自动计算并更新交付周期。",
  "Default Timezone": "默认时区",
  "Timezone used for all date and time calculations.": "所有日期与时间计算使用的时区。",
  "Date Format": "日期格式",
  "Select the default date format for the application.": "选择应用的默认日期格式。",
  "Communication connections": "通信连接",
  "Email Agent connection": "邮件智能体连接",
  "Email Agent": "邮件智能体",
  "Enable Email Agent": "启用邮件智能体",
  "Connect your verified company mailbox to ingest, triage and send email.": "连接已核验的公司邮箱，用于接收、分流和发送邮件。",
  "Runtime": "运行时",
  "Healthy": "正常",
  "Credential": "凭据",
  "Ready": "就绪",
  "External Verification": "外部验证",
  "Verified": "已核验",
  "Last Tested": "最近测试",
  "WhatsApp Agent connection": "WhatsApp 智能体连接",
  "WhatsApp Agent": "WhatsApp 智能体",
  "Enable WhatsApp Agent": "启用 WhatsApp 智能体",
  "Use the Meta WhatsApp Cloud API for approved templates and delivery receipts.": "使用 Meta WhatsApp Cloud API 发送已批准模板并获取送达回执。",
  "Not configured": "未配置",
  "Not verified": "未核验",
  "Never": "从未",
  "WeChat connection": "微信连接",
  "WeChat Agent": "微信智能体",
  "Enable WeChat Agent": "启用微信智能体",
  "Connect WeChat Work (企业微信) for notifications.": "连接企业微信以接收通知。",
  "Not available / Not configured": "不可用／未配置",
  "Blocked": "已阻止",

  "Purchase order detail": "采购订单详情",
  "Back to Overview": "返回总览",
  "Previous PO": "上一张采购订单",
  "Next PO": "下一张采购订单",
  "Items": "明细",
  "Documents": "文件",
  "History": "历史记录",
  "Communication": "沟通",
  "Purchase order metrics": "采购订单指标",
  "Total order value": "订单总金额",
  "Total Items": "明细总数",
  "Priced in USD": "以美元计价",
  "No verified stage timeline yet.": "暂无已核验的阶段时间线。",
  "Unnamed attachment": "未命名附件",
  "No verified stages": "暂无已核验阶段",
  "Purchase Order Details": "采购订单详情",
  "Port of Loading": "装货港",
  "Port of Discharge": "卸货港",
  "Country of Origin": "原产国",
  "PO Date": "采购订单日期",
  "Mode of Transport": "运输方式",
  "Currency": "币种",
  "Sent Date": "发送日期",
  "Payment Terms": "付款条款",
  "Confirmed": "已确认",
  "In progress": "进行中",
  "No notes yet.": "暂无备注。",
  "No attachments yet.": "暂无附件。",
  "Order Summary": "订单摘要",
  "Items Total": "明细金额",
  "Line Items": "明细行数",
  "Total": "合计",
  "Order Progress": "订单进度",
  "Risk & Details": "风险与详情",
  "Result": "结果",
  "Send Reminder": "发送提醒",
  "Purchase Order #": "采购订单 #",
  "Overdue by": "逾期",
  "Attachments (": "附件（",
  "Edit PO": "编辑采购订单",
  "Duplicate": "复制",
  "Download PDF": "下载 PDF",
  "Print": "打印",
  "Cancel PO": "取消采购订单",
  "Incoterm": "国际贸易术语",
  "The snapshot records": "该快照记录了",
  "high-risk POs; a read-only calculation over current POs finds": "张高风险采购订单；对当前采购订单进行只读计算后发现",
  ". Procurement facts changed after the snapshot. Charts and exports continue to use the immutable snapshot until you explicitly update it.": "张。快照生成后采购事实已发生变化；在您明确更新之前，图表和导出仍使用不可变快照。",
  "active POs": "进行中的采购订单",
  "Risk score 40-69": "风险评分 40–69",
  "Risk score 0-39": "风险评分 0–39",
  "historical points": "个历史数据点",
  "Risk trend line chart": "风险趋势折线图",
  "Risk breakdown radar chart": "风险构成雷达图",
  "days": "天",
  "day": "天",
  "Back to": "返回",
  "Created on": "创建于",
  "Attachments": "附件",
  "stages completed": "个阶段已完成",
  "Impact preview:": "影响预览：",
  "active purchase orders match the exact candidate.": "张进行中的采购订单与当前候选配置完全匹配。",
  "Items (": "明细（",
  "Search items": "搜索明细",
  "Search items, SKU, category…": "搜索明细、SKU 或类别…",
  "Filter items by category": "按类别筛选明细",
  "All categories": "全部类别",
  "Uncategorized": "未分类",
  "Item / Description": "物料／说明",
  "Category": "类别",
  "Ordered": "订购数量",
  "Unit": "单位",
  "Unit Price": "单价",
  "Tax": "税费",
  "Shipped": "已发运",
  "Received": "已收货",
  "Units": "件",
  "active": "启用",
  "Operating Profile": "运营信息",
  "Address": "地址",
  "Supplier Type": "供应商类型",
  "Industry": "行业",
  "Primary Material": "主要物料",
  "Default Lead Time": "默认交付周期",
  "Contract": "合同",
  "Missing": "缺失",
  "Search documents": "搜索文件",
  "Filter documents by status": "按状态筛选文件",
  "Filter documents by category": "按类别筛选文件",
  "All status": "全部状态",
  "Document Name": "文件名称",
  "Uploaded By": "上传人",
  "Uploaded On": "上传时间",
  "File Size": "文件大小",
  "Missing required documents": "缺少必需文件",
  "Purchase Order": "采购订单",
  "Supplier Confirmation": "供应商确认",
  "Total Activities": "活动总数",
  "Created On": "创建日期",
  "History Timeline": "历史时间线",
  "Track all persisted activities and changes for this purchase order.": "跟踪此采购订单所有已持久化的活动与变更。",
  "Filter purchase order history": "筛选采购订单历史记录",
  "All Activity": "全部活动",
  "Failed / Blocked": "失败／已阻止",
  "Amendments": "变更",
  "Inbound": "入站",
  "Outbound": "出站",
  "Pending Drafts": "待处理草稿",
  "Related Threads": "相关线程",
  "Readywork Procurement Execution keeps every PO on track with supervised supplier follow-up, delivery tracking, and evidence-backed risk identification from PO to GRN.": "Readywork 采购执行通过受监督的供应商催办、交付跟踪和有证据支持的风险识别，让每张采购订单从发出到收货都按计划推进。",
  "PROCUREMENT EXECUTION": "采购执行",
  "Authoritative tenant data appears after connection and validation.": "连接并核验后显示权威租户数据。",
  "Needs attention": "需要关注",
  "Awaiting receipt": "等待收货",
  "No persisted purchase orders": "暂无已持久化的采购订单",
  "Connect an approved source or import validated evidence to populate this workspace.": "连接获批来源或导入已核验证据后，工作区才会显示数据。",
  "Execution gates": "执行门禁",
  "Named identity": "实名身份",
  "SLA policy": "服务等级策略",
  "Only persisted operational events are shown.": "仅显示已持久化的运营事件。",
  "Requires action": "需要处理",
  "Supplier reply": "供应商回复",
  "No notifications yet": "暂无通知",
  "New items appear only when Readywork records a real source event or policy evaluation.": "只有 Readywork 记录真实来源事件或策略评估后，才会显示新事项。",
  "Review evidence and recipient before approving any send.": "批准发送前请核对证据和收件人。",
  "Pending review": "待审核",
  "No persisted drafts": "暂无已持久化的草稿",
  "Drafts appear after a real PO event and policy evaluation.": "真实采购订单事件和策略评估发生后才会生成草稿。",
  "Message review": "消息审核",
  "Recipient": "收件人",
  "PO LIFECYCLE": "采购订单生命周期",
  "Evidence-backed execution": "证据支持的执行",
  "No verified event": "暂无已核验事件",
  "Production": "生产",
  "Transit": "在途",
  "GRN": "收货",
  "Risk requires evidence coverage and a persisted model snapshot.": "风险判断需要证据覆盖和已持久化的模型快照。",
  "Portfolio risk": "采购组合风险",
  "Evidence coverage": "证据覆盖率",
  "Model snapshot": "模型快照",
  "Risk distribution": "风险分布",
  "Illustrative geometry only · no business values": "仅示意布局 · 不含业务数值",
  "The dashboard will not infer low risk from missing purchase-order evidence.": "看板不会因为采购订单证据缺失而推断为低风险。",
  "Route workbench": "路径工作台",
  "No persisted local purchase orders": "暂无已持久化的本地采购订单",
  "No persisted import purchase orders": "暂无已持久化的进口采购订单",
  "Route assignment appears only after a verified source or an auditable human decision.": "只有来源经过核验或人工决策可审计后，才会显示路径分配。",
  "Suggestions": "搜索建议",
  "confirmed": "已确认",
  "draft": "草稿",
  "RiskModelV2 uses real PO evidence frozen in each snapshot and weights Supplier Performance (30%), Delivery Delay (25%), PO Value (20%), Product Criticality (15%), and Compliance & Approval (10%). Insufficient coverage remains Provisional or Score not published; missing evidence is never treated as zero risk.": "RiskModelV2 使用每个快照中冻结的真实采购订单证据，权重分别为供应商绩效（30%）、交付延期（25%）、采购订单金额（20%）、产品关键程度（15%）和合规与审批（10%）。证据覆盖不足时保持为“暂定”或“评分未发布”；缺失证据绝不会被当作零风险。",
});

const DYNAMIC_RULES: ReadonlyArray<readonly [RegExp, (...parts: string[]) => string]> = [
  [/^Priced in ([A-Z]{3})$/, (currency) => `以 ${currency} 计价`],
  [/^(\d+) unclassified$/, (count) => `${count} 个未分类`],
  [/^(\d+) blockers$/, (count) => `${count} 项阻塞`],
  [/^Showing (\d+) to (\d+) of (\d+) entries$/, (from, to, total) => `显示第 ${from} 至 ${to} 项，共 ${total} 项`],
  [/^(\d+) purchase orders still await supplier confirmation\.$/, (count) => `${count} 张采购订单仍在等待供应商确认。`],
  [/^(\d+) purchase orders are past their required in-house date\.$/, (count) => `${count} 张采购订单已超过要求到厂日期。`],
  [/^(\d+) purchase orders require a human decision\.$/, (count) => `${count} 张采购订单需要人工决策。`],
  [/^(\d+) purchase orders are progressing on schedule\.$/, (count) => `${count} 张采购订单正在按计划推进。`],
  [/^Overdue\s+(\d+) d$/, (days) => `逾期 ${days} 天`],
  [/^Ask anything about your (.+)$/, (target) => `可询问与${target}有关的任何问题`],
  [/^Ask anything about (.+) POs…$/, (route) => `询问有关${route === "local" ? "本地采购" : "进口采购"}订单的任何问题…`],
  [/^Open purchase order (.+) execution context$/, (number) => `打开采购订单 ${number} 的执行上下文`],
  [/^(.+) actions$/, (number) => `${number} 操作`],
  [/^Rule (.+) will be removed\.$/, (rule) => `规则 ${rule} 将被移除。`],
  [/^(Local Procurement|Import Procurement): (High Risk|Awaiting Supplier|Delivery Risk|On Track)$/, (route, risk) => `${READYWORK_ZH_CN_TEXT[route] ?? route}：${READYWORK_ZH_CN_TEXT[risk] ?? risk}`],
  [/^(\d+) active POs need persisted route evidence; Readywork never guesses Local or Import from supplier, currency, or address\.$/, (count) => `${count} 张进行中的采购订单缺少已持久化的路径证据；Readywork 不会根据供应商、币种或地址猜测本地或进口路径。`],
  [/^(\d+) (minutes?|hours?|days?) ago$/, (count, unit) => `${count} ${unit.startsWith("minute") ? "分钟" : unit.startsWith("hour") ? "小时" : "天"}前`],
  [/^To: (.+) · (\d+) (minutes?|hours?|days?) ago$/, (recipient, count, unit) => `收件人：${recipient} · ${count} ${unit.startsWith("minute") ? "分钟" : unit.startsWith("hour") ? "小时" : "天"}前`],
  [/^(-?[\d.]+) days?$/, (count) => `${count} 天`],
  [/^Overdue by (\d+) days?$/, (days) => `逾期 ${days} 天`],
  [/^(\d+) \/ (\d+) POs$/, (count, total) => `${count} / ${total} 张采购订单`],
  [/^(\d+) active POs$/, (count) => `${count} 张进行中的采购订单`],
  [/^Snapshot (.+) · (\d+) historical points$/, (date, count) => `快照 ${date} · ${count} 个历史数据点`],
  [/^Risk score distribution for (\d+) purchase orders$/, (count) => `${count} 张采购订单的风险评分分布`],
  [/^Open full procurement context for (.+)$/, (number) => `打开 ${number} 的完整采购上下文`],
  [/^Page (\d+)$/, (page) => `第 ${page} 页`],
  [/^Edit supplier (.+)$/, (supplier) => `编辑供应商 ${supplier}`],
  [/^More actions for (.+)$/, (supplier) => `${supplier} 的更多操作`],
  [/^Purchase Order #(.+)$/, (number) => `采购订单 #${number}`],
  [/^Created on (.+) • (.+) • (.+)$/, (date, supplier, route) => `创建于 ${date} • ${supplier} • ${READYWORK_ZH_CN_TEXT[route] ?? route}`],
  [/^Attachments \((\d+)\)$/, (count) => `附件（${count}）`],
  [/^(\d+) of (\d+) stages completed$/, (count, total) => `已完成 ${count} / ${total} 个阶段`],
  [/^Showing (\d+) of (\d+) POs$/, (count, total) => `显示 ${count} / ${total} 张采购订单`],
  [/^(\d+) active POs remain in the route confirmation queue and will not appear here until confirmed\.$/, (count) => `${count} 张进行中的采购订单仍在路径确认队列中，确认前不会在此显示。`],
  [/^([A-Z]{3}) no change$/, (currency) => `${currency} 无变化`],
  [/^(Published|Provisional|Score not published) (\d+)$/, (label, count) => `${READYWORK_ZH_CN_TEXT[label] ?? label} ${count}`],
  [/^Filtered (\d+) \/ (\d+) POs$/, (count, total) => `已筛选 ${count} / ${total} 张采购订单`],
  [/^Showing (\d+) of (\d+) rules$/, (count, total) => `显示 ${count} / ${total} 条规则`],
  [/^The server is currently at version (\d+)\. Review the latest facts before resubmitting\.$/, (version) => `服务器当前版本为 ${version}。重新提交前请检查最新事实。`],
];

export const READYWORK_EN_TEXT: Readonly<Record<string, string>> = Object.freeze({
  ...Object.fromEntries(Object.entries(READYWORK_ZH_CN_TEXT).reverse().map(([english, chinese]) => [chinese, english])),
  ...enPlatform,
  ...enOrders,
  ...enSettings,
  ...ENGLISH_UI_OVERRIDES,
});
const ENGLISH_TEMPLATES = compileMessageTemplates(READYWORK_EN_TEXT);

export function translateReadyworkUiText(value: string, language: UiLanguage = "zh-CN"): string {
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const normalized = value.trim().replace(/\s+/g, " ");
  if (!normalized) return value;
  if (language === "en") {
    const exact = Object.hasOwn(READYWORK_EN_TEXT, normalized) ? READYWORK_EN_TEXT[normalized] : undefined;
    if (exact) return `${leading}${exact}${trailing}`;
    if (!/[\u3400-\u9fff]/u.test(normalized)) return value;
    for (const { pattern, prefix, suffix, target, slots } of ENGLISH_TEMPLATES) {
      if ((prefix && !normalized.startsWith(prefix)) || (suffix && !normalized.endsWith(suffix))) continue;
      const match = normalized.match(pattern);
      if (match) return `${leading}${target.replace(/\{\d+\}/g, (slot) => match[slots.indexOf(slot) + 1] ?? slot)}${trailing}`;
    }
    return value;
  }
  const exact = Object.hasOwn(READYWORK_ZH_CN_TEXT, normalized) ? READYWORK_ZH_CN_TEXT[normalized] : undefined;
  if (exact) return `${leading}${exact}${trailing}`;
  for (const [pattern, replacement] of DYNAMIC_RULES) {
    const match = normalized.match(pattern);
    if (match) return `${leading}${replacement(...match.slice(1))}${trailing}`;
  }
  return value;
}

const PRESERVE_SELECTOR = '[data-preserve-language], pre, code, script, style, [contenteditable="true"], [contenteditable=""], [contenteditable="plaintext-only"]';
const LOCALIZED_ATTRIBUTES = ["aria-label", "aria-description", "title", "placeholder", "alt"] as const;
type OriginalText = { source: string; rendered: string };
type OriginalNode = Map<string, OriginalText>;

// Kept under its previous export for compatibility with existing consumers/tests.
export function ChineseUiLocalization({ language = "zh-CN" }: { language?: UiLanguage } = {}) {
  const originals = useRef(new WeakMap<Node, OriginalNode>());
  useEffect(() => {
    document.documentElement.lang = language;
    function translated(node: Node, key: string, current: string, preserve: boolean): string {
      let fields = originals.current.get(node);
      if (!fields) { fields = new Map(); originals.current.set(node, fields); }
      const previous = fields.get(key);
      const source = previous?.rendered === current ? previous.source : current;
      const rendered = preserve ? source : translateReadyworkUiText(source, language);
      fields.set(key, { source, rendered });
      return rendered;
    }
    function localizeNode(node: Node) {
      if (node.nodeType === Node.TEXT_NODE) {
        const parent = node.parentElement;
        if (!parent) return;
        const current = node.nodeValue ?? "";
        const result = translated(node, "text", current, !!parent.closest(`${PRESERVE_SELECTOR}, textarea`));
        // Change text-node data only. Replacing elements would detach React's
        // nodes and break event handlers, reconciliation and unsaved form state.
        if (result !== current) node.nodeValue = result;
      } else if (node instanceof Element) {
        for (const attribute of LOCALIZED_ATTRIBUTES) {
          const current = node.getAttribute(attribute);
          if (!current) continue;
          const result = translated(node, attribute, current, !!node.closest(PRESERVE_SELECTOR));
          if (result !== current) node.setAttribute(attribute, result);
        }
      }
    }
    function localizeTree(root: Node) {
      localizeNode(root);
      if (!(root instanceof Element)) return;
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
      let node = walker.nextNode();
      while (node) { localizeNode(node); node = walker.nextNode(); }
    }
    const options: MutationObserverInit = {
      childList: true, subtree: true, characterData: true, attributes: true,
      attributeFilter: [...LOCALIZED_ATTRIBUTES, "data-preserve-language", "contenteditable"],
    };
    const observer = new MutationObserver((mutations) => {
      observer.disconnect();
      try {
        for (const mutation of mutations) {
          if (mutation.type === "characterData") localizeNode(mutation.target);
          if (mutation.type === "attributes") localizeTree(mutation.target);
          for (const node of mutation.addedNodes) localizeTree(node);
        }
      } finally {
        observer.observe(document.documentElement, options);
      }
    });
    localizeTree(document.documentElement);
    observer.observe(document.documentElement, options);
    return () => observer.disconnect();
  }, [language]);
  return null;
}
