import { ADVANCED_SLA_V2_PARAMETER_FIELDS, type AdvancedSlaDomain, type AdvancedSlaParameterFieldDefinition } from "@readywork/advanced-sla-contract";

/** Display-only system metadata. Never call this on a free-text business fact. */
const labels: Readonly<Record<string, string>> = {
  "Supplier Code": "供应商编码",
  "Supplier Name": "供应商名称",
  "Item Code": "物料编码",
  "Item Description": "物料说明",
  "Item Category": "物料类别",
  "Process Type": "流程类型",
  "Milestone Sequence": "里程碑顺序",
  "Milestone Name": "里程碑名称",
  "Next Milestone": "下一里程碑",
  "Blocking Milestone": "阻断性里程碑",
  "Standard Duration": "标准时长",
  "Duration Type": "时长类型",
  "Update Frequency": "更新频率",
  "Update Frequency Days": "更新间隔天数",
  "Expected Start Evidence": "预期开始证据",
  "Expected Completion Evidence": "预期完成证据",
  "Supplier Contact Role": "供应商联系人角色",
  "Stage": "阶段",
  "Event Type": "事件类型",
  "Initial Response SLA": "首次响应时限",
  "SLA Unit": "时限单位",
  "Reminder 1 After": "首次提醒等待时长",
  "Reminder 2 After": "第二次提醒等待时长",
  "Procurement Manager Flag After": "采购经理提醒等待时长",
  "Communication Channel": "沟通渠道",
  "Supplier Escalation Level 1": "供应商一级升级联系人",
  "Supplier Escalation Level 2": "供应商二级升级联系人",
  "Supplier Escalation Level 3": "供应商三级升级联系人",
  "Risk at Reminder 1": "首次提醒风险等级",
  "Risk at Reminder 2": "第二次提醒风险等级",
  "Risk at Escalation": "升级时风险等级",
  "Payment Term": "付款条款",
  "Payment Term Description": "付款条款说明",
  "Trigger Event": "触发事件",
  "Required Action": "所需操作",
  "Preparation Lead Time": "准备提前期",
  "Lead Time Unit": "提前期单位",
  "Completion SLA": "完成时限",
  "Reminder Rule": "提醒规则",
  "Flag Procurement Manager After": "采购经理提醒等待时长",
  "Blocking Stage": "阻断阶段",
  "Blocking Condition": "阻断条件",
  "Required Documents": "必需文件",
  "Responsible Function": "责任部门",
  "Risk Level": "风险等级",
  "LC Type": "信用证类型",
  "LC Opening Deadline": "信用证开立截止条件",
  "LC Preparation Lead Time": "信用证准备提前期",
  "LC Expiry Date Rule": "信用证到期日期规则",
  "Latest Shipment Date Rule": "最迟装运日期规则",
  "Presentation Period": "交单期限",
  "Partial Shipment Allowed": "允许分批装运",
  "Transshipment Allowed": "允许转运",
  "Confirmation Required": "需要保兑",
  "Advising Bank Required": "需要通知行",
  "Negotiation Bank Required": "需要议付行",
  "LC Amendment SLA": "信用证修改时限",
  "LC Document List": "信用证文件清单",
  "Discrepancy Review SLA": "不符点审核时限",
  "Incoterm": "国际贸易术语",
  "Transport Mode": "运输方式",
  "Origin Country": "起运国家／地区",
  "Origin Port": "起运港",
  "Destination Country": "目的国家／地区",
  "Destination Port": "目的港",
  "Freight Booking Owner": "订舱责任方",
  "Insurance Owner": "保险责任方",
  "Freight Planning Lead Time": "货运规划提前期",
  "Booking Confirmation Lead Time": "订舱确认提前期",
  "Pickup Planning Lead Time": "提货规划提前期",
  "Final Data Deadline": "最终资料截止条件",
  "Tentative Booking Allowed": "允许暂定订舱",
  "Estimated Data Required": "需要预估资料",
  "Parallel Logistics Thread Required": "需要并行物流会话",
  "Document / Information Name": "文件／信息名称",
  "Requirement Type": "要求类型",
  "Required From": "提供方",
  "Mandatory": "是否必需",
  "Validation Rule": "校验规则",
  "Required By Stage": "要求完成阶段",
  "Required By Milestone": "要求完成里程碑",
  "Tentative or Final": "暂定或最终",
  "Handover Recipient": "交接接收方",
  "Handover Method": "交接方式",
  "Missing Item Risk": "缺失项风险",
  "Origin": "起运地",
  "Destination": "目的地",
  "Standard Transit Time": "标准运输时长",
  "Transit Time Unit": "运输时长单位",
  "No Update SLA": "无更新时限",
  "ETA Change Threshold": "预计到达时间变更阈值",
  "Required Transit Events": "必需运输事件",
  "Source of Update": "更新来源",
  "Risk Escalation Rule": "风险升级规则",
  "HS Code": "HS 编码",
  "Customer Code": "客户编码",
  "Approval / Document Name": "审批／文件名称",
  "Regulatory Authority": "监管机构",
  "Required Before Stage": "须提前完成的阶段",
  "Application Lead Time": "申请提前期",
  "Approval Validity": "审批有效期",
  "Renewal Reminder": "续期提醒",
  "Required Supporting Documents": "必需支持文件",
  "Port / Airport": "港口／机场",
  "Customs Broker": "报关行",
  "Pre-Clearance Required": "需要预清关",
  "Pre-Clearance Lead Time": "预清关提前期",
  "Customs Document Deadline": "清关文件截止条件",
  "Clearance SLA": "清关时限",
  "Customs Update Frequency": "清关更新频率",
  "Duty Payment SLA": "关税缴纳时限",
  "Free Storage Days": "免费堆存天数",
  "Demurrage Start Day": "滞期费起算日",
  "Detention Start Day": "滞箱费起算日",
  "Flag Procurement Manager When": "采购经理提醒条件",
  "Risk Escalation Level": "风险升级等级",
  "Inspection Required": "需要检验",
  "Inspection Type": "检验类型",
  "Inspection Owner": "检验责任方",
  "Inspection SLA": "检验时限",
  "Required Test / Check": "必需测试／检查",
  "Acceptance Tolerance": "验收容差",
  "Required Inspection Document": "必需检验文件",
  "Quality Failure Action": "质量不合格处理",
  "Supplier Notification Required": "需要通知供应商",
  "GRN SLA": "收货单完成时限",
  "Partial GRN Allowed": "允许部分收货",
  "Scope": "适用范围",
  "Milestone": "里程碑",
  "Timing": "时限",
  "Evidence": "证据",
  "Escalation Levels": "升级层级",
  "Risk": "风险",
  "Terms": "条款",
  "Dependencies": "依赖项",
  "Documents": "文件",
  "Ownership": "责任分工",
  "LC Details": "信用证明细",
  "Route": "采购路线",
  "Lead Times": "提前期",
  "Booking": "订舱",
  "Requirement": "要求",
  "Handover": "交接",
  "Events": "事件",
  "Approval": "审批",
  "Clearance": "清关",
  "Charges": "费用",
  "Inspection": "检验",
  "Acceptance": "验收",
  "GRN": "收货单（GRN）",
  "Details": "详情",
  "Common": "通用信息",
  "Manufacturing": "制造",
  "Service": "服务",
  "Yes": "是",
  "No": "否",
  "Calendar Days": "自然日",
  "Working Days": "工作日",
  "Daily": "每天",
  "Every N Days": "每隔 N 天",
  "At Completion": "完成时",
  "Stage 1 — PO Sent": "阶段 1 — 采购订单已发送",
  "Stage 2 — Supplier Commitment": "阶段 2 — 供应商承诺",
  "Stage 3 — Fulfilment / Production": "阶段 3 — 履约／生产",
  "Stage 4 — Dispatch / Transit": "阶段 4 — 发运／运输",
  "Stage 5 — Delivery & Closure": "阶段 5 — 交付与关闭",
  "PI Pending": "形式发票待处理",
  "Milestone Update": "里程碑更新",
  "Document Pending": "文件待处理",
  "Payment Pending": "付款待处理",
  "Shipment Update": "发运更新",
  "Inspection Pending": "检验待处理",
  "GRN Pending": "收货单待处理",
  "Hours": "小时",
  "Days": "天",
  "Email": "邮件",
  "WeChat": "微信",
  "Low": "低",
  "Medium": "中",
  "High": "高",
  "100% Advance": "全额预付",
  "Partial Advance / Balance Before Shipment": "部分预付／装运前付清余款",
  "Letter of Credit (LC)": "信用证（LC）",
  "Cash Against Documents (CAD)": "凭单付款（CAD）",
  "Net 30": "30 天账期",
  "Net 60": "60 天账期",
  "Net 90": "90 天账期",
  "Open Account": "赊销",
  "Procurement": "采购",
  "Finance": "财务",
  "Logistics": "物流",
  "Compliance": "合规",
  "QA": "质量保证",
  "Warehouse": "仓库",
  "Supplier": "供应商",
  "Other": "其他",
  "Sight": "即期",
  "Usance": "远期",
  "Revolving": "循环",
  "Transferable": "可转让",
  "EXW — Ex Works": "EXW — 工厂交货",
  "FCA — Free Carrier": "FCA — 货交承运人",
  "FOB — Free On Board": "FOB — 船上交货",
  "CFR — Cost and Freight": "CFR — 成本加运费",
  "CIF — Cost, Insurance and Freight": "CIF — 成本、保险加运费",
  "CPT — Carriage Paid To": "CPT — 运费付至",
  "CIP — Carriage and Insurance Paid To": "CIP — 运费、保险费付至",
  "DAP — Delivered At Place": "DAP — 目的地交货",
  "DPU — Delivered at Place Unloaded": "DPU — 卸货地交货",
  "DDP — Delivered Duty Paid": "DDP — 完税后交货",
  "Sea": "海运",
  "Air": "空运",
  "Road": "公路运输",
  "Courier": "快递",
  "Buyer": "买方",
  "Document": "文件",
  "Data": "数据",
  "Tentative": "暂定",
  "Final": "最终",
  "System Thread": "系统会话",
  "Upload": "上传",
  "Milestone Based": "按里程碑",
  "Forwarder": "货运代理",
  "Event Based": "按事件",
  "Pre-shipment": "装运前",
  "Incoming": "到货",
  "Laboratory": "实验室",
  "Third Party": "第三方",
  "Hold": "暂缓",
  "Reject": "拒收",
  "Rework": "返工",
  "Replace": "更换",
  "Fabric, chemicals, service…": "织物、化学品、服务等",
  "Yarn Procurement, Knitting…": "纱线采购、针织等",
  "Primary supplier contact": "供应商主要联系人",
  "Supplier manager": "供应商经理",
  "Supplier senior management": "供应商高级管理人员",
  "PO issued, PI approved, BL issued…": "订单下发、形式发票批准、提单签发等",
  "Open LC, pay advance…": "开立信用证、支付预付款等",
  "Production / shipment / document release blocked": "阻断生产／装运／文件放行",
  "PI, LC, SWIFT, Payment Advice": "形式发票、信用证、SWIFT、付款通知",
  "Commercial Invoice, BL, COO…": "商业发票、提单、原产地证等",
  "Packing List, COO, CBM…": "装箱单、原产地证、体积等",
  "Match PO, valid, signed…": "与订单匹配、有效、已签署等",
  "Freight planning, booking, customs…": "货运规划、订舱、清关等",
  "Country / port": "国家／港口",
  "Booking, ETD, ATD, ETA, arrival…": "订舱、预计离港、实际离港、预计到达、到达等",
  "BOI approval, import licence…": "投资审批、进口许可等",
  "BOI, Customs, Municipality…": "投资审批机构、海关、市政机构等",
  "Production / shipment / customs block": "生产／装运／清关阻断",
  "Expiry period": "有效期限",
  "MSDS, Health Certificate…": "安全技术说明书、卫生证书等",
  "Defined trigger": "明确的触发条件",
  "GSM, shade, quantity…": "克重、色差、数量等",
  "e.g. ±2%": "例如：±2%",
  "Inspection report, lab report": "检验报告、实验室报告",
  "po_sent": "阶段 1 — 采购订单已发送",
  "supplier_commitment": "阶段 2 — 供应商承诺",
  "fulfilment_production": "阶段 3 — 履约／生产",
  "dispatch_transit": "阶段 4 — 发运／运输",
  "delivery_grn": "阶段 5 — 交付与关闭",
  "high": "高",
  "medium": "中",
  "low": "低",
  "all": "全部",
  "email": "邮件",
  "whatsapp": "WhatsApp",
  "wechat": "微信",
  "draft": "草稿",
  "active": "启用",
  "inactive": "停用",
  "published": "已发布",
  "retired": "已退役",
  "previewed": "已验证，未应用",
  "applied": "已应用",
  "failed": "失败",
  "error": "错误",
  "warning": "警告"
};

export function advancedSlaSystemLabel(value: string): string { return labels[value] ?? value; }

export const ADVANCED_SLA_CHINESE_PARAMETER_FIELDS = Object.fromEntries(
  Object.entries(ADVANCED_SLA_V2_PARAMETER_FIELDS).map(([domain, fields]) => [domain, fields.map((field) => ({
    ...field,
    label: advancedSlaSystemLabel(field.label),
    section: field.section ? advancedSlaSystemLabel(field.section) : undefined,
    placeholder: field.placeholder ? advancedSlaSystemLabel(field.placeholder) : undefined,
    options: field.options?.map((option) => ({ ...option, label: advancedSlaSystemLabel(option.label) })),
  }))]),
) as unknown as Record<AdvancedSlaDomain, readonly AdvancedSlaParameterFieldDefinition[]>;

export function advancedSlaParameterDisplay(domain: AdvancedSlaDomain, key: string, value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  const definition = ADVANCED_SLA_CHINESE_PARAMETER_FIELDS[domain].find((field) => field.key === key);
  if (definition?.kind === "select") return definition.options?.find((option) => option.value === value)?.label ?? String(value);
  if (definition?.kind === "boolean") return value === true ? "是" : value === false ? "否" : String(value);
  if (definition?.kind === "risk" || definition?.kind === "stage") return advancedSlaSystemLabel(String(value));
  if (definition?.kind === "channel_list" && Array.isArray(value)) return value.map((entry) => advancedSlaSystemLabel(String(entry))).join("、");
  return Array.isArray(value) ? value.length ? value.join(", ") : "—" : String(value);
}
