"use client";

import { uiConfirm } from "@/features/localization/ui-dialogs";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, FileCheck2, FileClock, FileUp, Loader2, RefreshCw, Save, ShieldCheck, X } from "lucide-react";
import { importDocumentProcessingView, type ProcessingTone } from "@/features/procurement/procurement-ui-state";
import { apiRequest, ReadyworkApiError } from "@/features/shared/api-client";
import { useProcurementLocale } from "@/features/procurement/tenant-preferences-context";
import { cn } from "@/lib/utils";

type Requirement = { code: string; name: string; description: string; required: boolean; requiredStage: "dispatch_transit" | "delivery_grn"; expiryRequired: boolean };
type Policy = { id: string; name: string; description: string; status: "draft" | "published" | "retired"; version: number; requirements: Requirement[]; publishedAt: string | null };
type DocumentItem = { id: string; requirementCode: string; attachmentId: string; documentNumber: string | null; issuedAt: string | null; expiresAt: string | null; version: number; fileName: string; sizeBytes: number; securityStatus: string; processingStatus: string; scanError: string | null; updatedAt: string };
type RequirementState = Requirement & { status: string; evidence: string; document?: DocumentItem };
type Evaluation = { status: string; version: number; evaluatedAt: string; summary: { stage?: string; requirements?: RequirementState[]; policyMissing?: boolean } };
type PurchaseOrder = { id: string; number: string; supplierId: string; status: string; stage: string; version: number; updatedAt: string; evaluation: Evaluation | null; documents: DocumentItem[]; events: Array<Record<string, unknown>> };
type Payload = { generatedAt: string | null; clamAvConfigured: boolean; policies: Policy[]; publishedPolicy: Policy | null; purchaseOrders: PurchaseOrder[]; permissions: { configure: boolean; approve: boolean; operate: boolean } };

const suggestedRequirements: Requirement[] = [
  { code: "commercial_invoice", name: "商业发票", description: "供应商签发的最终商业发票", required: true, requiredStage: "dispatch_transit", expiryRequired: false },
  { code: "packing_list", name: "装箱单", description: "包含箱数、毛净重和包装明细", required: true, requiredStage: "dispatch_transit", expiryRequired: false },
  { code: "transport_document", name: "运输单证", description: "提单、空运单或可验证的承运凭证", required: true, requiredStage: "dispatch_transit", expiryRequired: false },
  { code: "certificate_of_origin", name: "原产地证", description: "适用于需要原产地证明的进口订单", required: false, requiredStage: "dispatch_transit", expiryRequired: false },
  { code: "customs_declaration", name: "报关单", description: "交付与 GRN 完成前的进口申报凭证", required: true, requiredStage: "delivery_grn", expiryRequired: false },
];

const statusLabel: Record<string, string> = { passed: "已通过", on_track: "当前阶段无缺口", missing: "缺失", expired: "已过期", security_blocked: "安全阻断", policy_missing: "策略未发布" };
const statusTone: Record<string, string> = { passed: "bg-emerald-50 text-emerald-700", on_track: "bg-blue-50 text-blue-700", missing: "bg-amber-50 text-amber-700", expired: "bg-red-50 text-red-700", security_blocked: "bg-red-50 text-red-700", policy_missing: "bg-slate-100 text-slate-600" };
const processingTone: Record<ProcessingTone, string> = { green: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700", red: "bg-red-50 text-red-700", slate: "bg-slate-100 text-slate-600" };
function errorText(error: unknown): string { return error instanceof ReadyworkApiError ? error.message : error instanceof Error ? error.message : "进口单证请求失败"; }
function sizeText(bytes: number): string { return bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`; }
async function fileBase64(file: File): Promise<string> { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (let offset = 0; offset < bytes.length; offset += 8192) binary += String.fromCharCode(...bytes.subarray(offset, Math.min(bytes.length, offset + 8192))); return btoa(binary); }

export function ImportDocumentsPanel() {
  const { formatDate: dateText } = useProcurementLocale();
  const [data, setData] = useState<Payload | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [draftRequirements, setDraftRequirements] = useState<Requirement[]>([]);
  const [upload, setUpload] = useState<{ po: PurchaseOrder; requirement: Requirement } | null>(null); const [uploadFile, setUploadFile] = useState<File | null>(null); const [documentNumber, setDocumentNumber] = useState(""); const [issuedAt, setIssuedAt] = useState(""); const [expiresAt, setExpiresAt] = useState("");
  const abortRef = useRef<AbortController | null>(null);
  const load = useCallback(async () => { abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; setLoading(true); setError(null); try { const result = await apiRequest<Payload>("/api/procurement/import-documents", { signal: controller.signal }); if (!controller.signal.aborted) { setData(result); setSelectedId((current) => current && result.purchaseOrders.some((item) => item.id === current) ? current : result.purchaseOrders[0]?.id ?? null); const draft = result.policies.find((item) => item.status === "draft"); setDraftRequirements(draft?.requirements ?? []); } } catch (requestError) { if (!controller.signal.aborted) setError(errorText(requestError)); } finally { if (!controller.signal.aborted) setLoading(false); } }, []);
  useEffect(() => { void load(); return () => abortRef.current?.abort(); }, [load]);
  const draft = data?.policies.find((item) => item.status === "draft") ?? null; const selected = data?.purchaseOrders.find((item) => item.id === selectedId) ?? null;
  const metrics = useMemo(() => { const items = data?.purchaseOrders ?? []; return { total: items.length, passed: items.filter((item) => ["passed", "on_track"].includes(item.evaluation?.status ?? "")).length, missing: items.filter((item) => item.evaluation?.status === "missing" || item.evaluation?.status === "policy_missing").length, blocked: items.filter((item) => ["expired", "security_blocked"].includes(item.evaluation?.status ?? "")).length }; }, [data]);
  const metricCards: Array<{ label: string; value: number; icon: typeof FileCheck2; tone: string }> = [
    { label: "进口 PO", value: metrics.total, icon: FileCheck2, tone: "text-blue-600" },
    { label: "门禁通过", value: metrics.passed, icon: CheckCircle2, tone: "text-emerald-600" },
    { label: "缺少单证", value: metrics.missing, icon: FileClock, tone: "text-amber-600" },
    { label: "过期 / 安全阻断", value: metrics.blocked, icon: AlertTriangle, tone: "text-red-600" },
  ];

  async function createDraft() { setSaving(true); setError(null); try { await apiRequest("/api/procurement/import-documents/policies", { method: "POST", body: { name: "进口采购单证门禁 V1", description: "用于发运、清关与最终 GRN 的可审计单证要求。以下为建议草稿，发布前应由采购经理复核。", requirements: suggestedRequirements } }); setNotice("建议策略草稿已创建，尚未生效。"); await load(); } catch (requestError) { setError(errorText(requestError)); } finally { setSaving(false); } }
  async function saveDraft() { if (!draft) return; setSaving(true); setError(null); try { await apiRequest(`/api/procurement/import-documents/policies/${encodeURIComponent(draft.id)}`, { method: "PATCH", body: { expectedVersion: draft.version, requirements: draftRequirements } }); setNotice("单证策略草稿已保存。"); await load(); } catch (requestError) { setError(errorText(requestError)); } finally { setSaving(false); } }
  async function publishDraft() { if (!draft || !uiConfirm("发布后将立即成为进口 PO 完成门禁，并退役旧正式策略。确认发布？")) return; setSaving(true); setError(null); try { await apiRequest(`/api/procurement/import-documents/policies/${encodeURIComponent(draft.id)}/publish`, { method: "POST", body: { expectedVersion: draft.version } }); setNotice("进口单证策略已发布，全部进口 PO 已重新校验。"); await load(); } catch (requestError) { setError(errorText(requestError)); } finally { setSaving(false); } }
  async function refreshEvaluations() { setSaving(true); setError(null); try { await apiRequest("/api/procurement/import-documents/evaluate", { method: "POST", body: {} }); setNotice("进口 PO 单证状态已重新校验。"); await load(); } catch (requestError) { setError(errorText(requestError)); } finally { setSaving(false); } }
  async function submitUpload() { if (!upload || !uploadFile) return; setSaving(true); setError(null); try { await apiRequest(`/api/procurement/import-documents/pos/${encodeURIComponent(upload.po.id)}/documents`, { method: "POST", headers: { "Idempotency-Key": `import-document:${upload.po.id}:${upload.requirement.code}:${crypto.randomUUID()}` }, body: { requirementCode: upload.requirement.code, fileName: uploadFile.name, contentType: uploadFile.type || "application/octet-stream", contentBase64: await fileBase64(uploadFile), ...(documentNumber.trim() ? { documentNumber: documentNumber.trim() } : {}), ...(issuedAt ? { issuedAt } : {}), ...(expiresAt ? { expiresAt } : {}) } }); setUpload(null); setUploadFile(null); setDocumentNumber(""); setIssuedAt(""); setExpiresAt(""); setNotice("文件已保存并进入 ClamAV/解析队列；扫描明确通过前不会算作有效单证。"); await load(); } catch (requestError) { setError(errorText(requestError)); } finally { setSaving(false); } }

  if (loading && !data) return <section className="mt-5 flex min-h-72 items-center justify-center rounded-[22px] border border-[#e2e6ed] bg-white text-sm text-slate-500"><Loader2 className="mr-2 size-5 animate-spin" />正在读取进口单证门禁…</section>;
  return <section className="mt-5 space-y-5">
    <div className="rounded-[22px] border border-[#e2e6ed] bg-white p-6 shadow-[0_3px_14px_rgba(25,35,52,0.035)]">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><FileCheck2 className="size-5 text-[#2563eb]" /><h2 className="text-[18px] font-bold text-[#1f2937]">进口单证门禁</h2></div><p className="mt-2 max-w-3xl text-xs leading-5 text-[#7f8898]">文件、版本、签发/失效日期和 ClamAV 结果均来自持久化事实。进口 PO 的最终 GRN 只有在正式策略全部通过后才能完成。</p></div><button type="button" onClick={() => void refreshEvaluations()} disabled={saving} className="flex h-10 items-center gap-2 rounded-xl border border-[#dfe3eb] bg-white px-4 text-xs font-semibold text-[#596171]"><RefreshCw className={cn("size-4", saving && "animate-spin")} />重新校验</button></div>
      {error && <div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{notice && <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</div>}
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metricCards.map(({ label, value, icon: Icon, tone }) => <div key={label} className="rounded-2xl border border-[#e6e9ef] p-4"><div className="flex items-center justify-between text-xs font-semibold text-[#7d8594]"><span>{label}</span><Icon className={cn("size-4", tone)} /></div><div className="mt-3 text-2xl font-bold text-[#182236]">{value}</div></div>)}</div>
    </div>

    <div className="rounded-[22px] border border-[#e2e6ed] bg-white shadow-[0_3px_14px_rgba(25,35,52,0.035)]">
      <div className="flex flex-col justify-between gap-4 border-b border-[#edf0f4] px-6 py-5 sm:flex-row sm:items-center"><div><h3 className="text-[16px] font-bold text-[#273247]">正式策略</h3><p className="mt-1 text-xs text-[#8a92a1]">{data?.publishedPolicy ? `${data.publishedPolicy.name} · v${data.publishedPolicy.version} · ${data.publishedPolicy.requirements.filter((item) => item.required).length} 项必需单证` : "尚未发布策略；进口 PO 最终完成会安全阻断。"}</p></div><div className="flex gap-2">{!draft && data?.permissions.configure && <button type="button" onClick={() => void createDraft()} disabled={saving} className="h-9 rounded-xl border border-[#dfe3eb] px-4 text-xs font-semibold text-[#596171]">新建建议草稿</button>}{draft && <><button type="button" onClick={() => void saveDraft()} disabled={saving} className="flex h-9 items-center gap-2 rounded-xl border border-[#dfe3eb] px-4 text-xs font-semibold text-[#596171]"><Save className="size-3.5" />保存草稿</button>{data?.permissions.approve && <button type="button" onClick={() => void publishDraft()} disabled={saving} className="h-9 rounded-xl bg-[#2563eb] px-4 text-xs font-semibold text-white">发布门禁</button>}</>}</div></div>
      {draft ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-[#fafbfc] text-[10px] font-semibold uppercase tracking-[.08em] text-[#939aa8]"><th className="px-6 py-3">单证</th><th className="px-4 py-3">代码</th><th className="px-4 py-3">要求阶段</th><th className="px-4 py-3">必需</th><th className="px-4 py-3">失效日必填</th><th className="px-4 py-3">说明</th></tr></thead><tbody>{draftRequirements.map((item, index) => <tr key={item.code} className="border-t border-[#eef1f5] text-xs"><td className="px-6 py-3"><input value={item.name} onChange={(event) => setDraftRequirements((current) => current.map((entry, i) => i === index ? { ...entry, name: event.target.value } : entry))} className="h-9 w-36 rounded-lg border border-[#dfe3ea] px-3" /></td><td className="px-4 py-3 font-mono text-[#526078]">{item.code}</td><td className="px-4 py-3"><select value={item.requiredStage} onChange={(event) => setDraftRequirements((current) => current.map((entry, i) => i === index ? { ...entry, requiredStage: event.target.value as Requirement["requiredStage"] } : entry))} className="h-9 rounded-lg border border-[#dfe3ea] px-2"><option value="dispatch_transit">发运 / 在途</option><option value="delivery_grn">交付 / GRN</option></select></td><td className="px-4 py-3"><input type="checkbox" checked={item.required} onChange={(event) => setDraftRequirements((current) => current.map((entry, i) => i === index ? { ...entry, required: event.target.checked } : entry))} /></td><td className="px-4 py-3"><input type="checkbox" checked={item.expiryRequired} onChange={(event) => setDraftRequirements((current) => current.map((entry, i) => i === index ? { ...entry, expiryRequired: event.target.checked } : entry))} /></td><td className="px-4 py-3 text-[#758093]">{item.description}</td></tr>)}</tbody></table></div> : <div className="px-6 py-5 text-xs text-[#8a92a1]">当前没有待编辑草稿。发布策略后，如需修改，请新建下一版本草稿；旧版本会保留审计记录。</div>}
    </div>

    <div className="overflow-hidden rounded-[22px] border border-[#e2e6ed] bg-white shadow-[0_3px_14px_rgba(25,35,52,0.035)]"><div className="border-b border-[#edf0f4] px-6 py-5"><h3 className="text-[16px] font-bold text-[#273247]">进口 PO 单证状态</h3><p className="mt-1 text-xs text-[#8a92a1]">一张 PO 一行；点击后在下方查看缺口、原始文件和审计状态。</p></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="bg-[#fafbfc] text-[10px] font-semibold uppercase tracking-[.08em] text-[#939aa8]"><th className="px-6 py-3">PO</th><th className="px-4 py-3">阶段</th><th className="px-4 py-3">单证状态</th><th className="px-4 py-3">有效文件</th><th className="px-4 py-3">最后校验</th></tr></thead><tbody>{(data?.purchaseOrders ?? []).map((po) => { const evaluationStatus = po.evaluation?.status ?? "policy_missing"; return <tr key={po.id} onClick={() => setSelectedId(po.id)} className={cn("cursor-pointer border-t border-[#eef1f5] text-xs transition hover:bg-[#fafcff]", selectedId === po.id && "bg-[#f6f9ff]")}><td className="px-6 py-4 font-bold text-[#26334a]">{po.number}</td><td className="px-4 py-4 text-[#647086]">{po.stage}</td><td className="px-4 py-4"><span className={cn("rounded-full px-2.5 py-1 font-semibold", statusTone[evaluationStatus] ?? "bg-slate-100 text-slate-600")}>{statusLabel[evaluationStatus] ?? "状态待核验"}</span></td><td className="px-4 py-4 text-[#647086]">{po.documents.length}</td><td className="px-4 py-4 text-[#8a92a1]">{dateText(po.evaluation?.evaluatedAt)}</td></tr>; })}{!data?.purchaseOrders.length && <tr><td colSpan={5} className="px-6 py-14 text-center text-sm text-[#8a92a1]">当前没有具备可靠进口路线证据的 PO。系统不会根据供应商名称或国家猜测路线。</td></tr>}</tbody></table></div></div>

    {selected && <div className="rounded-[22px] border border-[#e2e6ed] bg-white p-6 shadow-[0_3px_14px_rgba(25,35,52,0.035)]"><div className="flex items-start justify-between"><div><h3 className="text-[17px] font-bold text-[#243047]">{selected.number} · 单证详情</h3><p className="mt-1 text-xs text-[#8a92a1]">扫描引擎：{data?.clamAvConfigured ? "ClamAV 已配置" : "未配置，所有上传文件将保持安全阻断"}</p></div><ShieldCheck className={cn("size-5", data?.clamAvConfigured ? "text-emerald-600" : "text-amber-600")} /></div><div className="mt-5 divide-y divide-[#edf0f4] rounded-2xl border border-[#e5e9ef]">{((selected.evaluation?.summary.requirements ?? data?.publishedPolicy?.requirements ?? []) as RequirementState[]).map((requirement) => { const document = selected.documents.find((item) => item.requirementCode === requirement.code) ?? requirement.document; const processing = document ? importDocumentProcessingView(document.processingStatus) : null; return <div key={requirement.code} className="flex flex-col gap-4 p-4 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-sm font-bold text-[#2b3548]">{requirement.name}</span>{requirement.required && <span className="rounded bg-red-50 px-1.5 py-0.5 text-[10px] font-semibold text-red-600">必需</span>}</div>{document ? <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-[#8791a1]"><span>{document.fileName} · {sizeText(document.sizeBytes)}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-600">安全：{document.securityStatus || "待核验"}</span>{processing && <span className={cn("rounded-full px-2 py-0.5 text-[10px] font-semibold", processingTone[processing.tone])}>解析：{processing.label}</span>}</div> : <div className="mt-1 text-xs text-[#8791a1]">{requirement.evidence ?? "尚未上传"}</div>}{document?.scanError && <div role="alert" className="mt-1 text-[11px] text-red-600">{document.scanError}</div>}</div><div className="text-xs text-[#738094]">{document?.expiresAt ? `失效：${dateText(document.expiresAt)}` : "无失效日期"}</div>{data?.permissions.operate && <button type="button" onClick={() => { setUpload({ po: selected, requirement }); setUploadFile(null); setDocumentNumber(""); setIssuedAt(""); setExpiresAt(""); }} className="flex h-9 items-center justify-center gap-2 rounded-xl border border-[#dfe3eb] px-4 text-xs font-semibold text-[#526078]"><FileUp className="size-3.5" />{document ? "上传新版本" : "上传文件"}</button>}</div>; })}</div></div>}

    {upload && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="w-full max-w-[540px] rounded-[24px] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-xl font-bold text-[#1d2739]">上传{upload.requirement.name}</h3><p className="mt-1 text-xs text-[#7f8998]">{upload.po.number} · 上传后先进入安全扫描，不会立即通过门禁。</p></div><button type="button" onClick={() => setUpload(null)} className="flex size-9 items-center justify-center rounded-xl bg-[#f2f4f7]"><X className="size-4" /></button></div><div className="mt-6 space-y-4"><label className="block rounded-2xl border border-dashed border-[#ccd4e1] bg-[#fafbfd] p-5 text-center text-xs text-[#667084]"><input type="file" className="sr-only" accept=".pdf,.png,.jpg,.jpeg,.txt,.csv,.docx,.xlsx" onChange={(event) => setUploadFile(event.target.files?.[0] ?? null)} /><FileUp className="mx-auto size-6 text-[#2563eb]" /><div className="mt-2 font-semibold">{uploadFile?.name ?? "选择本地文件"}</div><div className="mt-1 text-[10px] text-[#9aa1ad]">最大 8 MB；可执行文件与伪装 MIME 会被隔离</div></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-[#626c7d]">单证号码<input value={documentNumber} onChange={(event) => setDocumentNumber(event.target.value)} className="mt-2 h-10 w-full rounded-xl border border-[#dfe3ea] px-3 font-normal" /></label><label className="text-xs font-semibold text-[#626c7d]">签发日期<input type="date" value={issuedAt} onChange={(event) => setIssuedAt(event.target.value)} className="mt-2 h-10 w-full rounded-xl border border-[#dfe3ea] px-3 font-normal" /></label><label className="text-xs font-semibold text-[#626c7d]">失效日期{upload.requirement.expiryRequired && <span className="text-red-500"> *</span>}<input type="date" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} className="mt-2 h-10 w-full rounded-xl border border-[#dfe3ea] px-3 font-normal" /></label></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setUpload(null)} className="h-10 rounded-xl border border-[#dfe3ea] px-4 text-xs font-semibold text-[#626b7a]">取消</button><button type="button" onClick={() => void submitUpload()} disabled={saving || !uploadFile || (upload.requirement.expiryRequired && !expiresAt)} className="flex h-10 items-center gap-2 rounded-xl bg-[#2563eb] px-5 text-xs font-semibold text-white disabled:opacity-50">{saving && <Loader2 className="size-4 animate-spin" />}保存并扫描</button></div></div></div>}
  </section>;
}
