import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const source = readFileSync(
  fileURLToPath(new URL("../app/product/page.tsx", import.meta.url)),
  "utf8",
);
const formSource = readFileSync(
  fileURLToPath(new URL("../app/product/demo-request-form.tsx", import.meta.url)),
  "utf8",
);

test("public product Web: keeps the approved Readywork desktop page contract", () => {
  assert.match(source, /min-w-\[1180px\]/);
  assert.match(source, /overflow-x-clip/);
  assert.match(source, /style=\{\{ width: "calc\(100% - 5px\)" \}\}/);
  assert.match(source, /import \{ GeistSans \} from "geist\/font\/sans"/);
  assert.match(source, /GeistSans\.className/);
  assert.match(source, /sticky top-0/);
  assert.match(source, /id="problem" className="scroll-mt-20/);
  assert.match(source, /id="solution" className="scroll-mt-20/);
  assert.match(source, /box-border h-16 border-b border-\[rgba\(15,27,51,\.08\)\]/);
  assert.match(source, /absolute left-1\/2 flex -translate-x-1\/2 items-center gap-7 text-\[13\.5px\]/);
  assert.match(source, /href="#solution"/);
  assert.match(source, /查看产品概览/);
  assert.match(source, /Readywork 采购执行.*让每张采购订单.*按计划推进/);
  assert.match(source, /text-\[80px\]/);
  assert.match(source, /text-\[32px\]/);
  assert.match(source, /text-\[19px\]/);
  assert.match(source, /pt-\[72px\]/);
  assert.match(source, /mb-\[18px\] mt-5 text-\[80px\]/);
  assert.match(source, /mb-\[22px\] text-\[32px\]/);
  assert.match(source, /mb-16 flex h-12 items-center justify-center gap-3/);
  assert.match(source, /<BrowserShot label="Readywork 采购执行总览"[\s\S]*<ReadyworkProductVisual kind="overview" \/>/);
  assert.match(source, /pb-24/);
  assert.match(source, /提前识别风险/);
  assert.match(source, /const toolChips = \["SAP", "QuickBooks", "Gmail", "Outlook", "Office 365", "WhatsApp", "WeChat"\]/);
  assert.match(source, /function ToolIcon/);
  assert.match(source, /gap-\[14px\]/);
  assert.match(source, /rounded-\[10px\].*px-5 py-3 text-\[15px\] font-semibold/);
  assert.match(source, /电子邮件/);
  assert.match(source, /WhatsApp/);
  assert.match(source, /WeChat/);
  assert.match(source, /电话/);
  assert.match(source, /电子表格", "需要核验"/);
  assert.match(source, /grid-cols-\[minmax\(0,5fr\)_minmax\(0,3fr\)_minmax\(0,5fr\)\]/);
  assert.match(source, /strokeDasharray="3 5"/);
  assert.match(source, /id="problem" className="scroll-mt-20 border-t border-\[rgba\(15,27,51,\.08\)\] bg-\[#f3f6fa\] px-8 py-24"/);
  assert.match(source, /max-w-\[980px\] text-balance text-\[52px\]/);
  assert.match(source, /grid-cols-\[minmax\(0,5fr\)_minmax\(0,6fr\)\]/);
  assert.match(source, /id="gap" className="scroll-mt-20 border-t border-\[rgba\(15,27,51,\.08\)\] bg-\[#fafbfd\] px-8 py-24"/);
  assert.match(source, /max-w-\[760px\] text-balance text-\[52px\]/);
  assert.match(source, /text-\[16\.5px\] font-medium leading-\[1\.4\]/);
  assert.match(source, /relative pb-14 pr-6/);
  assert.match(source, /absolute bottom-0 right-0 w-\[280px\]/);
  assert.match(source, /max-w-\[1000px\]/);
  assert.match(source, /max-w-\[1000px\] text-balance/);
  assert.match(source, /mx-auto mt-14 max-w-\[1160px\]/);
  assert.match(source, /text-\[12px\].*leading-\[1\.55\].*tracking-\[0\.12em\].*text-\[#157f75\]/);
  assert.match(source, /function BrowserShot/);
  assert.match(source, /Readywork 起草催办，您的团队负责批准。/);
  assert.match(source, /不是系统通知，而是供应商认识的采购专业身份。/);
  assert.match(source, /grid-cols-\[minmax\(0,5fr\)_minmax\(0,6fr\)\]/);
  assert.match(source, /每条获接受的消息都与采购订单和连接器回执保持关联。/);
  assert.match(source, /每张采购订单都通过五个阶段管理/);
  assert.match(source, /id="how-it-works" className="scroll-mt-20 bg-\[#f3f6fa\] px-8 py-24"/);
  assert.match(source, /max-w-\[860px\] text-\[52px\]/);
  assert.match(source, /rounded-\[20px\].*border-\[rgba\(15,27,51,\.08\)\].*bg-\[#fafbfd\]/);
  assert.match(source, /<ol className="grid grid-cols-5">/);
  assert.match(source, /max-w-\[1360px\]/);
  assert.match(source, /bg-\[#2ec4b6\]/);
  assert.match(source, /absolute left-10 right-3 top-\[13px\] h-0\.5/);
  assert.match(source, /mt-16 grid grid-cols-\[minmax\(0,5fr\)_minmax\(0,6fr\)\] items-center gap-16/);
  assert.match(source, /max-w-\[560px\]/);
  assert.match(source, /rounded-\[14px\].*shadow-\[0_4px_8px/);
  assert.match(source, /只有持久化已核验的阶段证据后，生命周期视图才会显示内容。/);
  assert.match(source, /<ReadyworkProductVisual kind="po-timeline" \/>/);
  assert.match(source, /每个阶段都有 SLA 目标和宽限期/);
  assert.match(source, /通过电子邮件和 WhatsApp 持续催办/);
  assert.match(source, /物流交接前核验进口单据/);
  assert.doesNotMatch(source, /stage\.icon/);
  assert.match(source, /等到错过到期日时，[\s\S]*风险信号早已出现。/);
  assert.match(source, /id="risk-visibility" className="scroll-mt-20 border-t border-\[rgba\(15,27,51,\.08\)\] bg-\[#fafbfd\] px-8 py-24"/);
  assert.match(source, /<div className="mb-14">\s*<Eyebrow>风险洞察<\/Eyebrow>/);
  assert.match(source, /max-w-\[880px\] text-balance text-\[52px\]/);
  assert.match(source, /在错过交付前[\s\S]*发生在哪里。<\/span>/);
  assert.match(source, /max-w-\[720px\] text-\[18px\] leading-\[1\.55\] tracking-\[-0\.005em\] text-\[#46536b\]/);
  assert.match(source, /<ReadyworkProductVisual kind="risk-dashboard" \/>/);
  assert.match(source, /Readywork 风险看板：不使用示例业务指标展示证据覆盖率和风险状态/);
  assert.match(source, /className="mx-auto max-w-\[1160px\]"/);
  assert.match(source, /同一支团队，更大的执行能力。/);
  assert.match(source, /id="value" className="scroll-mt-20 border-t border-\[rgba\(15,27,51,\.08\)\] bg-\[#f3f6fa\] px-8 py-24"/);
  assert.match(source, /<Eyebrow>客户价值<\/Eyebrow>/);
  assert.match(source, /扩大采购执行能力<span className="text-\[#66738a\]">，而不是协调工作量。<\/span>/);
  assert.match(source, /grid h-\[432px\] grid-cols-\[minmax\(0,1fr\)_44px_minmax\(0,1fr\)\] items-center gap-6/);
  assert.match(source, /function ManualChannelIcon/);
  assert.match(source, /strokeDasharray="2\.5 3\.5"/);
  assert.match(source, /<ReadyworkProductVisual kind="route-local" \/>/);
  assert.match(source, /<ReadyworkProductVisual kind="route-import" \/>/);
  assert.doesNotMatch(source, /156 active|61 of 96|93 of 148|210 POs|\$2\.85M/);
  assert.match(source, /mx-auto mt-5 grid max-w-\[1160px\] grid-cols-2 gap-5/);
  assert.match(source, /id="why-us" className="scroll-mt-20 border-t border-\[rgba\(15,27,51,\.08\)\] bg-\[#f3f6fa\] px-8 py-14"/);
  assert.match(source, /mx-auto max-w-\[880px\] text-center/);
  assert.match(source, /mt-4 text-balance text-\[26px\] font-medium leading-\[1\.4\] tracking-\[-0\.02em\]/);
  assert.match(source, /id="faq" className="scroll-mt-20 border-t border-\[rgba\(15,27,51,\.08\)\] bg-\[#fafbfd\] px-8 py-24"/);
  assert.match(source, /mb-12 mt-5 text-balance text-\[52px\]/);
  assert.match(source, /group border-b border-\[rgba\(15,27,51,\.08\)\]/);
  assert.match(source, /gap-4 py-\[22px\] text-left/);
  assert.match(source, /text-\[16px\] font-medium leading-\[20\.5px\] tracking-\[-0\.01em\]/);
  assert.match(source, /size-\[18px\].*group-open:rotate-180/);
  assert.match(source, /max-w-\[720px\] flex-col gap-2\.5 pb-\[22px\]/);
  assert.match(source, /从限定范围的试点开始/);
  assert.match(source, /grid max-w-\[1360px\] grid-cols-\[minmax\(0,5fr\)_minmax\(0,6fr\)\] gap-16/);
  assert.match(source, /text-\[12px\].*tracking-\[0\.12em\].*text-\[#8fa1c0\]/);
  assert.match(source, /mb-6 mt-5 max-w-\[800px\] text-balance text-\[52px\]/);
  assert.match(source, /rounded-\[14px\] bg-\[#fafbfd\].*shadow-\[0_8px_16px/);
  assert.match(source, /h-\[5px\] bg-gradient-to-r from-\[#2ec4b6\] to-\[#4a6cf7\]/);
  assert.match(source, /px-\[30px\] pb-8 pt-\[30px\]/);
  assert.match(formSource, /flex flex-col gap-\[18px\]/);
  assert.match(formSource, /grid grid-cols-2 gap-\[18px\]/);
  assert.match(formSource, /rounded-\[6px\].*border-\[rgba\(15,27,51,\.14\)\].*bg-\[#fafbfd\]/);
  assert.match(formSource, /h-\[94px\] resize-y py-2\.5/);
  assert.match(formSource, /px-\[22px\] text-\[15px\] !font-medium tracking-\[-0\.005em\]/);
  assert.match(formSource, /-mt-1\.5 text-\[12\.5px\] leading-\[1\.5\]/);
  assert.match(formSource, /此表单不会触发供应商或 ERP 操作。/);
  assert.match(source, /footer className="border-t border-\[rgba\(15,27,51,\.08\)\] bg-\[#fafbfd\] px-8 pb-10 pt-16"/);
  assert.match(source, /mb-12 flex h-\[227\.75px\] max-w-\[1360px\] items-center gap-10/);
  assert.match(source, /Readywork 采购执行 · V1/);
  assert.match(source, /min-h-\[205\.461px\] max-w-\[1360px\] grid-cols-\[1\.4fr_1fr_1fr_1fr\] gap-12/);
  assert.match(source, /桌面网页 · 1280×720 \/ 1440×900 \/ 1920×1080/);
  assert.match(source, /<span>v1\.0\.0<\/span>/);
  assert.match(source, /<ChevronDown/);
  assert.doesNotMatch(source, /open=\{index === 0\}/);
  assert.doesNotMatch(source, /<Link href="\/"/);
  assert.doesNotMatch(source, /min-w-\[1180px\] overflow-hidden/);
});

test("public product Web: does not fabricate native mobile or third-party recognition claims", () => {
  assert.doesNotMatch(source, /mobile navigation|bottom action bar|UAE Startup Story Recognition|移动导航|底部操作栏|阿联酋创业故事认可/);
  assert.match(source, /href="\/privacy"/);
  assert.match(source, /href="\/terms"/);
  assert.match(source, /采购执行员 · 预发布版/);
  assert.doesNotMatch(source, /Privacy · pending|Terms · pending/);
});
